[build]
  command = "npm run build"
  publish = ".next"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "nft"
  external_node_modules = ["pg-native"]
