'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'sw' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  sw: {
    // Header
    'nav.home': 'Nyumbani',
    'nav.about': 'Kuhusu',
    'nav.how_it_works': 'Jinsi Inavyofanya Kazi',
    'nav.impact': 'Athari',
    'nav.join': 'Jiunge',
    'nav.investor': 'Wekeza',
    'nav.login': 'Ingia',
    
    // Hero Section
    'hero.title': 'Washika DAU – Kuunganisha Wajasiriamali na Ustawi wa Jamii',
    'hero.subtitle': 'Akiba. Mafunzo. Uwekezaji. Kila kitu unachohitaji kukua kiuchumi — katika jamii moja iliyounganishwa.',
    'hero.cta.entrepreneur': 'Jisajili Sasa',
    'hero.cta.investor': 'Shirikiana Nasi',
    'hero.learn_more': 'Jifunze',
    
    // About Section
    'about.title': 'Kuhusu Washika DAU',
    'about.vision.title': 'Maono',
    'about.vision.text': 'Kuwa kitovu cha maendeleo ya kijamii na kiuchumi kinacholenga kujenga uchumi wa mzunguko endelevu.',
    'about.mission.title': 'Dhamira',
    'about.mission.text': 'Kuwawezesha wajasiriamali wadogo kupitia mafunzo, mtandao, na uongozi wa kiuchumi.',
    'about.values.title': 'Maadili',
    'about.values.text': 'Uwazi, Ushirikiano, Uongozi, na Maendeleo Endelevu.',
    
    // How It Works
    'how_it_works.title': 'Jinsi Washika DAU Inavyofanya Kazi',
    'how_it_works.step1.title': 'Uanachama na Mafunzo',
    'how_it_works.step1.text': 'Wajasiriamali wanajiunga kupitia vikundi, kulipa ada ndogo ya kila mwezi, na kupata mafunzo.',
    'how_it_works.step2.title': 'Uwekezaji wa Mtaji',
    'how_it_works.step2.text': 'Washika DAU inawekeza katika vikundi, hisa ya 30% ya uongozi.',
    'how_it_works.step3.title': 'Uchumi wa Mzunguko',
    'how_it_works.step3.text': 'Rasilimali zinazunguka ndani ya mtandao.',
    'how_it_works.step4.title': 'Ustawi wa Pamoja',
    'how_it_works.step4.text': 'Faida na mgao wa faida vinashirikiwa.',
    
    // Impact
    'impact.title': 'Athari Yetu',
    'impact.groups': 'Vikundi',
    'impact.cbts': 'CBTs',
    'impact.businesses': 'Biashara',
    'impact.growing': 'Mtandao Unaokua',
    
    // Registration
    'registration.title': 'Jisajili kwa Washika DAU',
    'registration.name': 'Jina Kamili',
    'registration.contact': 'Mawasiliano (Simu/Barua pepe)',
    'registration.location': 'Mahali',
    'registration.business_type': 'Aina ya Biashara',
    'registration.group_name': 'Jina la Kundi (ikiwa tayari uko katika kimoja)',
    'registration.gender': 'Jinsia',
    'registration.age': 'Umri',
    'registration.submit': 'Wasilisha',
    
    // Investor Section
    'investor.title': 'Kwa Nini Uwekeze na Washika DAU?',
    'investor.subtitle': 'Mfumo wa hisa ya 30%, uongozi wa kijamii, athari endelevu.',
    'investor.cta': 'Pakua Hati za Mwekezaji',
    'investor.eyebrow': 'Wekeza',
    'investor.intro': 'Tunashirikiana na wawekezaji ambao wanaelewa kwamba ukuaji wa kweli unaanzia katika jamii.',
    'investor.card1.title': 'Mfumo wa Hisa',
    'investor.card1.text': 'Unapowekeza katika kundi la Washika DAU, unapata hisa ya moja kwa moja ndani ya biashara zao. Mapato yanashirikiwa kwa uwazi kulingana na mikataba iliyowekwa wazi.',
    'investor.card2.title': 'Ufuatiliaji wa Wakati Halisi',
    'investor.card2.text': 'Kila muamala, malipo, na mkutano wa kundi unaweza kuonekana kupitia dashibodi yetu. Uwazi kamili — hakuna siri.',
    'investor.card3.title': 'Athari ya Kijamii',
    'investor.card3.text': 'Uwekezaji wako unasaidia wajasiriamali wadogo kupata mtaji, mafunzo, na mtandao wa kuwaendeleza biashara zao.',
    'investor.contact': 'Wasiliana nasi',

    // Hero extras
    'hero.motto': 'Pamoja Tunajengana',
    'hero.cta.join': 'Jiunge Sasa',
    'hero.stat.groups': 'Vikundi',
    'hero.stat.businesses': 'Biashara',
    'hero.stat.trainers': 'Wakufunzi',
    'hero.stat.trainings': 'Mafunzo',
    'hero.stat.volume': 'Kiasi kilichopita',
    'hero.stat.held': 'Kwenye vikundi',
    'hero.stat.liveNote': 'Takwimu halisi kutoka jukwaani',
    'hero.node.save': 'Weka Akiba',
    'hero.node.learn': 'Jifunze',
    'hero.node.invest': 'Wekeza',
    'hero.node.center': 'Jamii',
    'hero.live': 'Moja kwa moja',
    'hero.ticker.1': 'Asha ameweka akiba TSh 50,000',
    'hero.ticker.2': 'Kikundi THE BOYS FC kimefadhili mradi',
    'hero.ticker.3': 'Juma amekamilisha mafunzo ya biashara',
    'hero.ticker.4': 'Mwekezaji ameunga mkono kikundi kipya',

    // About / process rail
    'about.eyebrow': 'Mchakato Wetu',
    'about.heading': 'Washika DAU mfumo wa vikundi kidijitali',
    'about.subheading': 'Fuata hatua hizi nne za kimsingi kujiunge na jamii yetu ya wajasiriamali',

    // Join CTA
    'join.eyebrow': 'Jiunge',
    'join.title': 'Jiunge na sisi Leo',

    // Login page
    'login.welcome.l1': 'Karibu tena',
    'login.welcome.l2': 'kwenye jamii yako',
    'login.welcome.sub': 'Ingia kuendelea na safari yako ya biashara, mafunzo, na uwekezaji pamoja na wenzako.',
    'login.feature1': 'Fuatilia uwekezaji wako',
    'login.feature2': 'Endelea na masomo na vyeti',
    'login.feature3': 'Shirikiana na kundi lako',
    'login.heading': 'Ingia',
    'login.no_account': 'Bado huna akaunti?',
    'login.register_here': 'Jisajili hapa',
    'login.field.identifier': 'Barua pepe au nambari ya simu',
    'login.ph.identifier': '07xx xxx xxx au email@example.com',
    'login.field.password': 'Nywila',
    'login.ph.password': 'Weka nywila yako',
    'login.forgot': 'Umesahau?',
    'login.remember': 'Nikumbuke kwenye kifaa hiki',
    'login.submit': 'Ingia',
    'login.submitting': 'Inaingia...',

    // Register page
    'register.welcome.l1': 'Jiunge na jamii',
    'register.welcome.l2': 'ya wajasiriamali',
    'register.welcome.sub': 'Sajili leo na uanze safari yako ya biashara, mafunzo, na uwekezaji pamoja na wenzako.',
    'register.feature1': 'Mafunzo ya biashara na vyeti',
    'register.feature2': 'Vikundi vya akiba na uwekezaji',
    'register.feature3': 'Malipo ya M-Pesa yaliyosalimishwa',
    'register.feature4': 'Fuatilia ukuaji wa biashara yako',
    'register.heading': 'Unda Akaunti',
    'register.have_account': 'Una akaunti tayari?',
    'register.login_here': 'Ingia hapa',
    'register.section.personal': 'Taarifa za Kibinafsi',
    'register.section.business': 'Biashara na Kitambulisho',
    'register.section.password': 'Unda Nywila',
    'register.f.fullname': 'Jina Kamili',
    'register.ph.fullname': 'Jina lako kamili',
    'register.f.phone': 'Nambari ya Simu',
    'register.f.email': 'Barua Pepe',
    'register.optional': '(si lazima)',
    'register.f.location': 'Mji / Mkoa',
    'register.f.gender': 'Jinsia',
    'register.opt.select_gender': 'Chagua jinsia',
    'register.gender.female': 'Mwanamke',
    'register.gender.male': 'Mwanamume',
    'register.f.age': 'Umri',
    'register.ph.age': 'Umri wako',
    'register.f.business': 'Aina ya Biashara',
    'register.opt.select_type': 'Chagua aina',
    'register.biz.agriculture': 'Kilimo',
    'register.biz.livestock': 'Ufugaji',
    'register.biz.small': 'Biashara Ndogo',
    'register.biz.arts': 'Sanaa na Ubunifu',
    'register.biz.services': 'Huduma',
    'register.biz.tech': 'Teknolojia',
    'register.biz.other': 'Nyingine',
    'register.f.idtype': 'Aina ya Kitambulisho',
    'register.id.national': 'Kitambulisho cha Taifa',
    'register.id.voter': 'Kitambulisho cha Mpiga Kura',
    'register.id.passport': 'Paspoti',
    'register.f.idnumber': 'Nambari ya Kitambulisho',
    'register.ph.idnumber': 'Ingiza nambari ya kitambulisho',
    'register.f.password': 'Nywila',
    'register.ph.password': 'Nywila yenye nguvu',
    'register.f.confirm': 'Thibitisha Nywila',
    'register.ph.confirm': 'Rudia nywila',
    'register.submit': 'Unda Akaunti',
    'register.submitting': 'Inasajili...',
    'register.terms': 'Kwa kusajili, unakubali masharti na sera ya faragha ya Washika DAU.',
    'register.err.mismatch': 'Nywila hazifanani',
    'register.success.title': 'Umefanikiwa!',
    'register.success.text': 'Akaunti yako imeundwa. Unaweza sasa kuingia kwenye jukwaa.',
    'register.success.cta': 'Ingia Sasa',
    'register.register_another': 'Sajili mtu mwingine',

    // Common
    'common.platform': 'Jukumu Platform',
    'tagline': 'Jukwaa la Wajasiriamali Tanzania',

    // Member dashboard — navigation
    'dash.nav.overview': 'Muhtasari',
    'dash.nav.wallet': 'Pochi',
    'dash.nav.group': 'Kundi',
    'dash.nav.investments': 'Uwekezaji',
    'dash.nav.training': 'Mafunzo',
    'dash.nav.settings': 'Mipangilio',
    'dash.nav.more': 'Zaidi',
    'dash.logout': 'Toka',
    // Member dashboard — overview
    'dash.greeting': 'Habari',
    'dash.overview.subtitle': 'Hapa kuna muhtasari wa akaunti yako',
    'dash.balance.label': 'Salio Lako',
    'dash.action.deposit': 'Weka Pesa',
    'dash.action.withdraw': 'Toa Pesa',
    'dash.action.transfer': 'Hamisha',
    'dash.stat.membership': 'Hali ya Uanachama',
    'dash.stat.active': 'Hai',
    'dash.stat.pending': 'Inasubiri',
    'dash.stat.mygroup': 'Kundi Langu',
    'dash.stat.nogroup': 'Hujajiunga',
    'dash.stat.investment': 'Uwekezaji Wangu',
    'dash.stat.returns': 'Faida Inayotarajiwa',
    'dash.governance.title': 'Maamuzi ya Kikundi',
    'dash.governance.sub': 'Shiriki katika kupiga kura na maazimio ya kundi lako',
    'dash.activity.title': 'Shughuli za Hivi Karibuni',
    'dash.joined': 'Umejiunga na Washika DAU',
    'dash.quicknav.title': 'Nenda Haraka',
    'dash.quicknav.wallet': 'Wallet Yangu',
    'dash.quicknav.wallet.sub': 'Historia na mabadiliko ya salio',
    'dash.quicknav.group': 'Kundi Langu',
    'dash.quicknav.group.sub': 'Angalia wanachama na shughuli',
    'dash.quicknav.training': 'Mafunzo',
    'dash.quicknav.training.sub': 'Endelea na masomo',
    'dash.quicknav.investment': 'Uwekezaji',
    'dash.quicknav.investment.sub': 'Fuatilia mapato yako',
    'dash.member': 'Mwanachama',

    // Group detail — tabs & roles
    'grp.tab.overview': 'Muhtasari',
    'grp.tab.members': 'Wanachama',
    'grp.tab.leadership': 'Uongozi',
    'grp.tab.fedha': 'Fedha',
    'grp.tab.decisions': 'Maamuzi',
    'grp.role.leader': 'Kiongozi',
    'grp.role.chairman': 'Mwenyekiti',
    'grp.role.secretary': 'Katibu',
    'grp.role.treasurer': 'Mweka Hazina',
    'grp.role.member': 'Mwanachama',
    'grp.founded': 'Ilianzishwa',
    'mg.title': 'Makundi Yangu',
    'mg.subtitle': 'Makundi unayoshiriki nayo',
    'mg.create': 'Unda Kundi',
    'mg.creating': 'Inaunda...',
    'mg.status': 'Hali',
    'mg.perMonth': 'kwa mwezi',
    'mg.perWeek': 'kwa wiki',
    'mg.tapToView': 'Gusa kuangalia kundi',
    'mg.view': 'Angalia',
    'mg.joinAnother': 'Jiunge na Kundi Jingine',
    'mg.joinCta': 'Jiunge na Kundi',
    'mg.emptyTitle': 'Bado hujajiunga na kundi lolote.',
    'mg.emptyHint': 'Pata nambari ya kundi (mfano: JKM-A3F9K2) kutoka kwa kiongozi.',
    'mg.myRequests': 'Maombi Yangu',
    'mg.month': 'mwezi',
    'mg.week': 'wiki',
    'mg.role.member': 'mwanachama',
    'mg.status.pending': 'Inasubiri',
    'mg.status.approved': 'Imeidhinishwa',
    'mg.status.rejected': 'Imekataliwa',
    'mg.createNew.title': 'Unda Kundi Jipya',
    'mg.createNew.desc': 'Utakuwa kiongozi wa kundi hili moja kwa moja.',
    'mg.field.name': 'Jina la Kundi',
    'mg.field.namePh': 'Mfano: Vikundi vya Maendeleo',
    'mg.field.logo': 'Nembo ya Kundi (si lazima)',
    'mg.field.logoUpload': 'Pakia nembo',
    'mg.field.logoHelper': 'Picha ya mraba inafaa zaidi. Itapunguzwa kiotomatiki.',
    'set.field.avatar': 'Picha ya Wasifu',
    'set.field.avatarHelper': 'Picha ya mraba inafaa zaidi. Itapunguzwa kiotomatiki.',
    'img.change': 'Badilisha',
    'img.remove': 'Ondoa',
    'mg.field.voting': 'Kiwango cha Kupiga Kura',
    'mg.field.of': 'kati ya',
    'mg.field.pass': 'kura kupita',
    'mg.field.currently': 'Sasa hivi',
    'mg.field.votesNeeded': 'kura zinahitajika kupitisha pendekezo',
    'mg.cancel': 'Ghairi',
    'mg.joinModal.title': 'Jiunge na Kundi',
    'mg.joinModal.desc': 'Ingiza nambari ya kundi uliyopewa na kiongozi.',
    'mg.joinModal.codePh': 'Mfano: JKM-A3F9K2',
    'mg.joinModal.search': 'Tafuta',
    'mg.joinModal.leader': 'Kiongozi',
    'mg.joinModal.unassigned': 'Hajapewa',
    'mg.joinModal.members': 'wanachama',
    'mg.joinModal.open': 'Wazi — utajiunga moja kwa moja',
    'mg.joinModal.needsApproval': 'Inahitaji idhini ya kiongozi',
    'mg.joinModal.messageLabel': 'Ujumbe kwa kiongozi (si lazima)',
    'mg.joinModal.messagePh': 'Eleza kwa nini ungependa kujiunga...',
    'mg.joinModal.joinNow': 'Jiunga Sasa',
    'mg.joinModal.sendReq': 'Tuma Ombi',
    'mg.joinModal.joining': 'Inajiunga...',
    'grp.copy': 'Nakili',
    'grp.copied': 'Imenakiliwa!',
    'grp.newProposal': '+ Pendekezo',
    'grp.treasury.balance': 'Salio la Hazina',
    'grp.treasury.balanceDesc': 'Fedha za kundi zinazodhibitiwa na mapendekezo yaliyoidhinishwa',
    'grp.stat.members': 'Wanachama',
    'grp.stat.monthly': 'Mchango/Mwezi',
    'grp.stat.contribution': 'Mchango',
    'grp.stat.collected': 'Jumla Iliyokusanywa',
    'grp.stat.paidThisMonth': 'Waliolipa Mwezi Huu',
    'grp.stat.thisMonth': 'Mwezi Huu',
    'grp.stat.disbursed': 'Jumla Iliyotumwa',
    'grp.treasury.title': 'Hazina ya Kundi',
    'grp.treasury.subtitle': 'Fedha za kundi zinazodhibitiwa na mapendekezo.',
    'grp.refresh': 'Onyesha upya',
    'grp.recentActivity': 'Shughuli za Hivi Karibuni',
    'grp.noActivity': 'Hakuna shughuli bado',
    'grp.treasuryNotOpen': 'Hazina haijafunguliwa bado',
    'grp.recentProposals': 'Mapendekezo ya Hivi Karibuni',
    'grp.viewAll': 'Angalia yote',
    'grp.groupWord': 'Kundi',
    'grp.ptype.general': 'Jumla',
    'grp.ptype.ask': 'Ombi',
    'grp.ptype.spend': 'Matumizi',
    'grp.noMembers': 'Hakuna wanachama bado',
    'grp.noMembersDesc': 'Wanachama wataonekana hapa baada ya kujiunga',
    'grp.noLeadership': 'Hakuna uongozi bado',
    'grp.sendToMember': 'Tuma Fedha kwa Mwanachama',
    'grp.sendDesc': 'Tuma pesa moja kwa moja kupitia mobile money.',
    'grp.recipientName': 'Jina la Mpokeaji',
    'grp.phone': 'Nambari ya Simu',
    'grp.send': 'Tuma Fedha',
    'grp.noPayments': 'Hakuna malipo bado',
    'grp.noProposals': 'Hakuna mapendekezo bado',
    'grp.leadersCanPropose': 'Viongozi wanaweza kuunda mapendekezo',
    'grp.newProposalTitle': 'Pendekezo Jipya',
    'grp.propTitle': 'Kichwa cha Pendekezo',
    'grp.recipientPhone': 'Simu ya Mpokeaji',
    'grp.vendorName': 'Jina la Muuzaji',
    'grp.projectDuration': 'Muda wa Mradi',
    'grp.propDescPh': 'Eleza pendekezo lako kwa undani zaidi...',
    'grp.projectDesc': 'Maelezo ya Mradi',
    'grp.createProposal': 'Unda Pendekezo',
    'grp.depositToWallet': 'Weka Fedha Mfukoni',
    'grp.ussdHint': 'Utapokea arifa ya USSD kwenye simu yako. Ingiza PIN kuthibitisha.',
    'grp.dontClose': 'Usifunge ukurasa huu hadi malipo yakamilike.',
    'grp.invalidPhone': 'Ingiza nambari sahihi ya simu',
    'grp.sending': 'Inatuma...',
    'grp.creating': 'Inaunda...',
    'grp.payContribution': 'Lipa Mchango',
    'grp.regularContribution': 'Mchango wa kawaida',
    'grp.perMonth': 'mwezi',
    'grp.proposals': 'Mapendekezo',
    'grp.proposalsWord': 'pendekezo',
    'grp.newProposalBtn': 'Pendekezo Jipya',
    'grp.clickToStart': 'Bonyeza "Pendekezo Jipya" kuanza',
    'grp.target': 'Lengo',
    'grp.statusOpen': 'Wazi',
    'grp.statusClosed': 'Imefungwa',
    'grp.by': 'na',

    // Wallet
    'wal.balance': 'Salio la Wallet',
    'wal.deposit': 'Weka Pesa',
    'wal.withdraw': 'Toa Pesa',
    'wal.transfer': 'Hamisha',
    'wal.transferFull': 'Hamisha Pesa',
    'wal.history': 'Historia ya Miamala',
    'wal.noTx': 'Hakuna miamala bado',
    'wal.sending': 'Inatuma...',
    'wal.amount': 'Kiasi (TSh)',
    'wal.phone': 'Nambari ya Simu',
    'wal.username': 'Username ya Mwanachama',
    'wal.usernameHint': 'Ingiza username ya mwanachama (herufi ndogo, nambari, na _ tu)',
    'wal.success': 'Imefanikiwa!',
    'wal.type': 'Aina',
    'wal.contribution': 'Mchango kwa Kundi',
    'wal.p2p': 'Tuma kwa Mwanachama',
    'wal.chooseGroup': 'Chagua Kundi',
    'wal.loading': 'Inapakia...',
    'wal.noGroups': 'Hujajiunga na kundi lolote',
    'wal.recipientUsername': 'Username ya Mpokezi',
    'wal.chooseGroupPh': '-- Chagua kundi --',
    'wal.amountTzs': 'Kiasi (TZS)',
    'wal.phoneShort': 'Namba ya Simu',

    // Settings
    'set.username.title': 'Username ya Uhamisho Pesa',
    'set.username.hasDesc': 'Wenzako wanaweza kukutumia pesa kwa kutumia username yako',
    'set.username.noDesc': 'Weka username yako ili wenzako waweze kukutumia pesa kwa urahisi',
    'set.username.yours': 'Username yako',
    'set.username.checking': 'Inakagua...',
    'set.username.available': '✓ Inapatikana',
    'set.username.taken': '✗ Imechukuliwa',
    'set.username.hint': 'Herufi ndogo, nambari, na _ tu (3-30 vibambo)',
    'set.username.saved': '✓ Imehifadhiwa!',
    'set.username.saving': 'Inahifadhi...',
    'set.username.save': 'Hifadhi Username',
    'set.menu.account': 'Taarifa za Akaunti',
    'set.menu.account.desc': 'Jina, nambari ya simu, barua pepe',
    'set.menu.security': 'Usalama',
    'set.menu.security.desc': 'Nywila na uthibitishaji',
    'set.menu.notifications': 'Arifa',
    'set.menu.notifications.desc': 'Mipangilio ya arifa',
    'set.menu.language': 'Lugha',
    'set.comingSoon': 'Hivi karibuni',

    // Notifications
    'notif.title': 'Arifa',
    'notif.markAllRead': 'Soma zote',
    'notif.viewAll': 'Angalia zote',
    'notif.empty': 'Hakuna arifa bado',
    'notif.emptyDesc': 'Arifa za miamala, vikundi na mapendekezo zitaonekana hapa.',
    'notif.all': 'Zote',
    'notif.unread': 'Hazijasomwa',
    'notif.enablePush': 'Washa arifa za simu',
    'notif.pushEnabled': 'Arifa za simu zimewashwa',
    'notif.pushDenied': 'Umezuia arifa. Ruhusu kwenye mipangilio ya kivinjari.',
    'notif.pushUnsupported': 'Kifaa hiki hakiungi mkono arifa za simu.',
    'notif.justNow': 'Sasa hivi',
    'notif.minAgo': 'dakika',
    'notif.hourAgo': 'saa',
    'notif.dayAgo': 'siku',

    // Proposal detail
    'prop.type.general': 'Jumla',
    'prop.type.ask': 'Ombi',
    'prop.type.spend': 'Matumizi',
    'prop.type.prodcast': 'Prodcast',
    'prop.type.general.desc': 'Majadiliano na upigaji kura wa kawaida — bila malipo.',
    'prop.type.ask.desc': 'Ombi la fedha kutoka hazina ya kundi kwa ajili ya biashara yako.',
    'prop.type.spend.desc': 'Matumizi ya pamoja ya kundi — kwa muuzaji au huduma.',
    'prop.type.prodcast.desc': 'Tangaza mradi kwa wawekezaji kupitia portal ya uwekezaji.',
    'prop.title.ph.general': 'k.m. Ongeza mchango wa kila mwezi',
    'prop.title.ph.ask': 'k.m. Mkopo wa mtaji wa biashara',
    'prop.title.ph.spend': 'k.m. Ada ya mkutano wa mafunzo',
    'prop.title.ph.prodcast': 'k.m. Mradi wa kilimo cha umwagiliaji',
    'prop.amount': 'Kiasi (TSH)',
    'prop.amount.ph': 'k.m. 500000',
    'prop.recipientPhone.ph': 'k.m. 0712345678',
    'prop.vendorName.ph': 'k.m. Duka la vifaa',
    'prop.expenseCategory': 'Aina ya Matumizi',
    'prop.expenseCategory.ph': 'k.m. Vifaa, Mafunzo, Tukio...',
    'prop.fundingGoal': 'Lengo la Fedha (TSH)',
    'prop.fundingGoal.ph': 'k.m. 5000000',
    'prop.timeline.ph': 'k.m. Miezi 6',
    'prop.impact': 'Athari Inayotarajiwa',
    'prop.impact.ph': 'k.m. Kuongeza mapato kwa 30%',
    'prop.desc.label': 'Maelezo',
    'prop.desc.optional': '(si lazima)',
    'prop.projectDesc.ph': 'Eleza mradi wako kwa wawekezaji...',
    'prop.info.general': 'Wanachama wote wa kundi wataweza kupiga kura baada ya pendekezo kuundwa.',
    'prop.info.ask': 'Fedha zitahamishwa moja kwa moja kwenye pochi yako baada ya kura kupita.',
    'prop.info.spend': 'Wanachama wote wa kundi wataweza kupiga kura baada ya pendekezo kuundwa.',
    'prop.info.prodcast': 'Baada ya kura kupita, mradi utaonekana kwa wawekezaji kwenye portal.',
    'prop.cancel': 'Ghairi',
    'prop.attachment': 'Kiambatisho (picha/faili)',
    'prop.attachment.add': 'Pakia picha au PDF',
    'prop.attachment.helper': 'Picha au PDF hadi 2MB — k.m. risiti, nukuu ya bei, au picha ya mradi.',
    'prop.attachment.err': 'Faili halikubaliki au ni kubwa mno.',
    'prop.attachment.view': 'Fungua kiambatisho',
    'prop.err.titleRequired': 'Kichwa cha pendekezo kinahitajika.',
    'prop.err.amountInvalid': 'Ingiza kiasi halali.',
    'prop.err.phoneRequired': 'Ingiza nambari ya simu ya mpokeaji.',
    'prop.err.goalInvalid': 'Ingiza lengo la fedha.',
    'prop.err.createFailed': 'Imeshindikana kuunda pendekezo.',
    'prop.err.genericFailed': 'Imeshindikana.',
    'prop.success.created': 'Pendekezo limeundwa!',
    'prop.backToGroup': 'Rudi Kwa Kundi',
    'prop.by': 'na',
    'prop.open': 'Wazi',
    'prop.closed': 'Imefungwa',
    'prop.abstain': 'Jiepushe',
    'prop.totalVotes': 'Jumla',
    'prop.votes': 'kura',
    'prop.needed': 'zinahitajika',
    'prop.yourVote': 'Kura yako',
    'prop.recipient': 'Mpokeaji',
    'prop.recipientPhone': 'Nambari ya simu ya mpokeaji',
    'prop.status.paid': 'Imelipwa',
    'prop.status.pending': 'Inasubiri',
    'prop.leaderAction': 'Kitendo cha Uongozi',
    'prop.status': 'Hali',
    'prop.amountPh': 'k.m. 5000',
    'prop.chooseMember': 'Chagua mwanachama',
    'prop.notEnoughVotes': 'Pendekezo halikupata kura za kutosha',
    'prop.notEnoughVotesTail': 'Unaweza kufungua kura tena au kutengeneza pendekezo jipya.',
    'prop.detailsHeading': 'Maelezo ya Pendekezo',
    'prop.field.fundingGoal': 'Lengo la Fedha',
    'prop.field.timeline': 'Muda',
    'prop.field.impact': 'Athari Inayotarajiwa',
    'prop.field.projectDesc': 'Maelezo ya mradi',
    'prop.field.vendor': 'Muuzaji',
    'prop.field.expenseCategory': 'Aina ya Matumizi',
    'prop.field.businessPurpose': 'Kusudi la Biashara',
    'prop.type.pillGeneral': 'Jumla',
    'prop.type.pillAsk': 'Ombi la Fedha',
    'prop.type.pillSpend': 'Matumizi',
    'prop.type.pillProdcast': 'Prodcast (Mwekezaji)',
    'prop.results': 'Matokeo ya Kura',
    'prop.yes': 'Ndio',
    'prop.no': 'Hapana',
    'prop.vote': 'Piga Kura',
    'prop.votingClosed': 'Upigaji kura umefungwa',
    'prop.canChange': 'Unaweza kubadilisha kura yako wakati wowote.',
    'prop.allCanVote': 'Wanachama wote wa kundi wanaweza kupiga kura.',
    'prop.amountRequested': 'Kiasi kilichoombwa',
    'prop.paymentStatus': 'Hali ya malipo',
    'prop.pending': 'Inasubiri',
    'prop.passed': 'Pendekezo limepita kura ✓ — unaweza kulipa kutoka hazina ya kundi.',
    'prop.amountTzs': 'Kiasi (TZS)',
    'prop.executing': 'Inatekeleza...',
    'prop.disburse': 'Tekeleza Malipo (Disburse)',
    'prop.fromTreasury': 'Itatolewa kwenye salio la hazina ya kundi.',
    'prop.reopenVoting': 'Fungua Kura Tena (Re-open voting)',
    'prop.err.notAllowed': 'Huruhusiwi kuona pendekezo hili.',
    'prop.err.loadFailed': 'Imeshindikana kupakua pendekezo.',
    'prop.err.voteFailed': 'Imeshindikana kupiga kura.',
    'prop.err.invalidAmount': 'Weka kiasi sahihi cha malipo.',
    'prop.err.payFailed': 'Imeshindikana kutekeleza malipo.',
    'prop.err.reopenFailed': 'Imeshindikana kufungua kura.',
    'prop.reopenSuccess': 'Kura zimefunguliwa tena. Wanachama wanaweza kupiga kura.',
    'prop.chooseRecipient': 'Chagua mpokeaji.',
    'prop.paid': 'Malipo yamekamilika! (Funds disbursed)',

    // Share group
    'share.button': 'Shiriki',
    'share.title': 'Shiriki Kundi',
    'share.desc': 'Waalike wenzako wajiunge na kundi lako',
    'share.copy': 'Nakili Kiungo',
    'share.copied': 'Imenakiliwa!',
    'share.more': 'Zaidi',
    'share.msgJoin': 'Jiunge na kundi',
    'share.msgCode': 'Tumia namba ya kundi',
    'share.msgOn': 'kwenye WashikaDAU',

    // Contribution frequency
    'grp.freq.label': 'Mzunguko wa Mchango',
    'grp.freq.monthly': 'Kila Mwezi',
    'grp.freq.weekly': 'Kila Wiki',
    'grp.freq.contribAmount': 'Mchango',
    'grp.settings.title': 'Mipangilio ya Kundi',
    'grp.settings.save': 'Hifadhi Mabadiliko',
    'grp.settings.saving': 'Inahifadhi...',
    'grp.settings.saved': 'Mipangilio yamehifadhiwa!',
    'grp.settings.leadershipOnly': 'Uongozi pekee unaweza kubadilisha mipangilio.',

    // Investor portal
    'inv.nav.overview': 'Muhtasari',
    'inv.nav.projects': 'Miradi',
    'inv.nav.groups': 'Vikundi',
    'inv.nav.wallet': 'Pochi',
    'inv.nav.profile': 'Wasifu',
    'inv.investorPortal': 'Lango la Wawekezaji',
    'inv.publicPage': 'Ukurasa wa Umma',
    'inv.signOut': 'Toka',
    'inv.contact': 'Wasiliana',
    'inv.welcome': 'Karibu',
    'inv.overviewSub': 'Hapa kuna muhtasari wa fursa za uwekezaji kwenye mtandao wa WashikaDAU.',
    'inv.stat.activeProjects': 'Miradi Inayoendelea',
    'inv.stat.approvedProdcasts': 'Prodcasts Zilizoidhinishwa',
    'inv.stat.fundingSought': 'Fedha Zinazohitajika',
    'inv.stat.totalRequested': 'Jumla iliyoombwa',
    'inv.stat.groups': 'Vikundi',
    'inv.stat.active': 'Hai',
    'inv.stat.members': 'Wanachama',
    'inv.stat.regions': 'mikoa',
    'inv.recentlyVoted': 'Miradi Iliyopigiwa Kura',
    'inv.viewAll': 'Angalia yote',
    'inv.activeGroups': 'Vikundi Hai',
    'inv.investmentProjects': 'Miradi ya Uwekezaji',
    'inv.approvedByVote': 'miradi iliyoidhinishwa kwa kura ya wanachama',
    'inv.noProjects': 'Hakuna miradi bado',
    'inv.noData': 'Hakuna data bado',
    'inv.wallet.title': 'Pochi ya nTZS',
    'inv.wallet.sub': 'Weka, toa, au hamisha fedha kupitia mtandao wa Base.',
    'inv.wallet.balance': 'Salio la Pochi',
    'inv.deposit': 'Weka Pesa',
    'inv.withdraw': 'Toa Pesa',
    'inv.recentTx': 'Miamala ya Hivi Karibuni',
    'inv.noTx': 'Hakuna miamala bado',
    'inv.profile.title': 'Wasifu Wako',
    'inv.profile.sub': 'Taarifa zako za mwekezaji',
    'inv.edit': 'Hariri',
    'inv.verified': 'Akaunti Imethibitishwa',
    'inv.pending': 'Inasubiri Uthibitisho',
    'inv.pendingSub': 'Timu yetu itawasiliana nawe ndani ya siku 2 za kazi',
    'inv.field.fullName': 'Jina Kamili',
    'inv.field.email': 'Barua Pepe',
    'inv.field.company': 'Kampuni',
    'inv.field.country': 'Nchi',
    'inv.field.type': 'Aina',
    'inv.field.minInvestment': 'Uwekezaji wa Chini',
    'inv.field.maxInvestment': 'Uwekezaji wa Juu',
    'inv.fund': 'Fadhili',
    'inv.seekingVote': 'Inatafuta Kura',
    'inv.communityApproved': 'Imeidhinishwa na Jamii',
    'inv.awaitingApproval': 'Inasubiri idhini ya jamii',
    'inv.communityVote': 'Kura ya Jamii',
    'inv.contribution': 'Mchango',
    'inv.about': 'Kuhusu Mradi',
    'inv.expectedImpact': 'Athari Inayotarajiwa',
    'inv.noDataSub': 'Miradi ya Prodcast itaonekana hapa mara itakapoidhinishwa na vikundi',
    'inv.noProjectsSub': 'Vikundi vitawasilisha miradi hapa kupitia mchakato wa kupiga kura',
    'inv.approvedByVote2': 'imeidhinishwa na kura za wanachama',
    'inv.col.group': 'Kikundi',
    'inv.col.members': 'Wanachama',
    'inv.col.contribution': 'Mchango wa Mwezi',
    'inv.col.projects': 'Miradi',
    'inv.fundingGoal': 'Lengo la Ufadhili',
    'inv.timeline': 'Muda',
    'inv.backToProjects': 'Rudi kwenye miradi',
    'inv.members': 'wanachama',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.how_it_works': 'How It Works',
    'nav.impact': 'Impact',
    'nav.investor': 'Invest',
    'nav.join': 'Join',
    'nav.login': 'Login',
    
    // Hero Section
    'hero.title': 'Washika DAU – Connecting Entrepreneurs with Community Prosperity',
    'hero.subtitle': 'We empower small entrepreneurs through training, networks, and economic leadership for a sustainable circular economy.',
    'hero.cta.entrepreneur': 'Register Now',
    'hero.cta.investor': 'Partner With Us',
    'hero.learn_more': 'Learn More',
    
    // About Section
    'about.title': 'About Washika DAU',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be a center for social and economic development that aims to build a sustainable circular economy.',
    'about.mission.title': 'Mission',
    'about.mission.text': 'To empower small entrepreneurs through training, networks, and economic leadership.',
    'about.values.title': 'Values',
    'about.values.text': 'Transparency, Collaboration, Leadership, and Sustainable Development.',
    
    // How It Works
    'how_it_works.title': 'How Washika DAU Works',
    'how_it_works.step1.title': 'Membership & Training',
    'how_it_works.step1.text': 'Entrepreneurs join via groups, pay small monthly fees, and receive training.',
    'how_it_works.step2.title': 'Capital Investment',
    'how_it_works.step2.text': 'Washika DAU invests in groups with a 30% equity stake.',
    'how_it_works.step3.title': 'Circular Economy',
    'how_it_works.step3.text': 'Resources circulate within the network.',
    'how_it_works.step4.title': 'Shared Prosperity',
    'how_it_works.step4.text': 'Profits and dividends are shared back.',
    
    // Impact
    'impact.title': 'Our Impact',
    'impact.groups': 'Groups',
    'impact.cbts': 'CBTs',
    'impact.businesses': 'Businesses',
    'impact.growing': 'Growing Network',
    
    // Registration
    'registration.title': 'Register with Washika DAU',
    'registration.name': 'Full Name',
    'registration.contact': 'Contact (Phone/Email)',
    'registration.location': 'Location',
    'registration.business_type': 'Business Type',
    'registration.group_name': 'Group Name (if already in one)',
    'registration.gender': 'Gender',
    'registration.age': 'Age',
    'registration.submit': 'Submit',
    
    // Investor Section
    'investor.title': 'Why Invest with Washika DAU?',
    'investor.subtitle': '30% equity model, community-driven, sustainable impact.',
    'investor.cta': 'Download Investor Deck',
    'investor.eyebrow': 'Invest',
    'investor.intro': 'We partner with investors who understand that true growth starts within the community.',
    'investor.card1.title': 'Equity Model',
    'investor.card1.text': 'When you invest in a Washika DAU group, you receive direct equity in their businesses. Returns are shared transparently based on clearly defined agreements.',
    'investor.card2.title': 'Real-time Tracking',
    'investor.card2.text': 'Every transaction, payment, and group meeting is visible through our dashboard. Full transparency — no secrets.',
    'investor.card3.title': 'Social Impact',
    'investor.card3.text': 'Your investment helps small entrepreneurs access capital, training, and a network to grow their businesses.',
    'investor.contact': 'Contact us',

    // Hero extras
    'hero.motto': 'Together We Build',
    'hero.cta.join': 'Join Now',
    'hero.stat.groups': 'Groups',
    'hero.stat.businesses': 'Businesses',
    'hero.stat.trainers': 'Trainers',
    'hero.stat.trainings': 'Trainings',
    'hero.stat.volume': 'Volume processed',
    'hero.stat.held': 'Held in groups',
    'hero.stat.liveNote': 'Live figures from the platform',
    'hero.node.save': 'Save',
    'hero.node.learn': 'Learn',
    'hero.node.invest': 'Invest',
    'hero.node.center': 'Community',
    'hero.live': 'Live',
    'hero.ticker.1': 'Asha saved TSh 50,000',
    'hero.ticker.2': 'Group THE BOYS FC funded a project',
    'hero.ticker.3': 'Juma completed business training',
    'hero.ticker.4': 'An investor backed a new group',

    // About / process rail
    'about.eyebrow': 'Our Process',
    'about.heading': 'Washika DAU — a digital groups platform',
    'about.subheading': 'Follow these four essential steps to join our community of entrepreneurs',

    // Join CTA
    'join.eyebrow': 'Join',
    'join.title': 'Join Us Today',

    // Login page
    'login.welcome.l1': 'Welcome back',
    'login.welcome.l2': 'to your community',
    'login.welcome.sub': 'Sign in to continue your journey of business, training, and investment with your peers.',
    'login.feature1': 'Track your investments',
    'login.feature2': 'Continue your courses and certificates',
    'login.feature3': 'Collaborate with your group',
    'login.heading': 'Sign In',
    'login.no_account': "Don't have an account yet?",
    'login.register_here': 'Register here',
    'login.field.identifier': 'Email or phone number',
    'login.ph.identifier': '07xx xxx xxx or email@example.com',
    'login.field.password': 'Password',
    'login.ph.password': 'Enter your password',
    'login.forgot': 'Forgot?',
    'login.remember': 'Remember me on this device',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',

    // Register page
    'register.welcome.l1': 'Join the community',
    'register.welcome.l2': 'of entrepreneurs',
    'register.welcome.sub': 'Register today and start your journey of business, training, and investment with your peers.',
    'register.feature1': 'Business training and certificates',
    'register.feature2': 'Savings and investment groups',
    'register.feature3': 'Secure M-Pesa payments',
    'register.feature4': 'Track your business growth',
    'register.heading': 'Create Account',
    'register.have_account': 'Already have an account?',
    'register.login_here': 'Sign in here',
    'register.section.personal': 'Personal Information',
    'register.section.business': 'Business & ID',
    'register.section.password': 'Create Password',
    'register.f.fullname': 'Full Name',
    'register.ph.fullname': 'Your full name',
    'register.f.phone': 'Phone Number',
    'register.f.email': 'Email',
    'register.optional': '(optional)',
    'register.f.location': 'City / Region',
    'register.f.gender': 'Gender',
    'register.opt.select_gender': 'Select gender',
    'register.gender.female': 'Female',
    'register.gender.male': 'Male',
    'register.f.age': 'Age',
    'register.ph.age': 'Your age',
    'register.f.business': 'Business Type',
    'register.opt.select_type': 'Select type',
    'register.biz.agriculture': 'Agriculture',
    'register.biz.livestock': 'Livestock',
    'register.biz.small': 'Small Business',
    'register.biz.arts': 'Arts & Crafts',
    'register.biz.services': 'Services',
    'register.biz.tech': 'Technology',
    'register.biz.other': 'Other',
    'register.f.idtype': 'ID Type',
    'register.id.national': 'National ID',
    'register.id.voter': 'Voter ID',
    'register.id.passport': 'Passport',
    'register.f.idnumber': 'ID Number',
    'register.ph.idnumber': 'Enter ID number',
    'register.f.password': 'Password',
    'register.ph.password': 'Strong password',
    'register.f.confirm': 'Confirm Password',
    'register.ph.confirm': 'Repeat password',
    'register.submit': 'Create Account',
    'register.submitting': 'Registering...',
    'register.terms': "By registering, you agree to Washika DAU's terms and privacy policy.",
    'register.err.mismatch': 'Passwords do not match',
    'register.success.title': 'Success!',
    'register.success.text': 'Your account has been created. You can now sign in to the platform.',
    'register.success.cta': 'Sign In Now',
    'register.register_another': 'Register another person',

    // Common
    'common.platform': 'Jukumu Platform',
    'tagline': 'Empowering Entrepreneurs, Building a Circular Economy.',

    // Member dashboard — navigation
    'dash.nav.overview': 'Overview',
    'dash.nav.wallet': 'Wallet',
    'dash.nav.group': 'My Group',
    'dash.nav.investments': 'Investments',
    'dash.nav.training': 'Training',
    'dash.nav.settings': 'Settings',
    'dash.nav.more': 'More',
    'dash.logout': 'Logout',
    // Member dashboard — overview
    'dash.greeting': 'Hello',
    'dash.overview.subtitle': "Here's a summary of your account",
    'dash.balance.label': 'Your Balance',
    'dash.action.deposit': 'Deposit',
    'dash.action.withdraw': 'Withdraw',
    'dash.action.transfer': 'Transfer',
    'dash.stat.membership': 'Membership Status',
    'dash.stat.active': 'Active',
    'dash.stat.pending': 'Pending',
    'dash.stat.mygroup': 'My Group',
    'dash.stat.nogroup': 'Not joined',
    'dash.stat.investment': 'My Investment',
    'dash.stat.returns': 'Expected Returns',
    'dash.governance.title': 'Group Decisions',
    'dash.governance.sub': "Take part in your group's votes and resolutions",
    'dash.activity.title': 'Recent Activity',
    'dash.joined': 'Joined Washika DAU',
    'dash.quicknav.title': 'Quick Links',
    'dash.quicknav.wallet': 'My Wallet',
    'dash.quicknav.wallet.sub': 'History and balance changes',
    'dash.quicknav.group': 'My Group',
    'dash.quicknav.group.sub': 'View members and activity',
    'dash.quicknav.training': 'Training',
    'dash.quicknav.training.sub': 'Continue your courses',
    'dash.quicknav.investment': 'Investment',
    'dash.quicknav.investment.sub': 'Track your returns',
    'dash.member': 'Member',

    // Group detail — tabs & roles
    'grp.tab.overview': 'Overview',
    'grp.tab.members': 'Members',
    'grp.tab.leadership': 'Leadership',
    'grp.tab.fedha': 'Finances',
    'grp.tab.decisions': 'Decisions',
    'grp.role.leader': 'Leader',
    'grp.role.chairman': 'Chairman',
    'grp.role.secretary': 'Secretary',
    'grp.role.treasurer': 'Treasurer',
    'grp.role.member': 'Member',
    'grp.founded': 'Founded',
    'mg.title': 'My Groups',
    'mg.subtitle': 'Groups you belong to',
    'mg.create': 'Create Group',
    'mg.creating': 'Creating...',
    'mg.status': 'Status',
    'mg.perMonth': 'per month',
    'mg.perWeek': 'per week',
    'mg.tapToView': 'Tap to view group',
    'mg.view': 'View',
    'mg.joinAnother': 'Join Another Group',
    'mg.joinCta': 'Join a Group',
    'mg.emptyTitle': "You haven't joined any group yet.",
    'mg.emptyHint': 'Get a group code (e.g. JKM-A3F9K2) from a leader.',
    'mg.myRequests': 'My Requests',
    'mg.month': 'month',
    'mg.week': 'week',
    'mg.role.member': 'member',
    'mg.status.pending': 'Pending',
    'mg.status.approved': 'Approved',
    'mg.status.rejected': 'Rejected',
    'mg.createNew.title': 'Create a New Group',
    'mg.createNew.desc': "You'll automatically become the leader of this group.",
    'mg.field.name': 'Group Name',
    'mg.field.namePh': 'e.g. Development Circle',
    'mg.field.logo': 'Group Logo (optional)',
    'mg.field.logoUpload': 'Upload logo',
    'mg.field.logoHelper': 'A square photo works best. It will be resized automatically.',
    'set.field.avatar': 'Profile Photo',
    'set.field.avatarHelper': 'A square photo works best. It will be resized automatically.',
    'img.change': 'Change',
    'img.remove': 'Remove',
    'mg.field.voting': 'Voting Threshold',
    'mg.field.of': 'of',
    'mg.field.pass': 'votes to pass',
    'mg.field.currently': 'Currently',
    'mg.field.votesNeeded': 'votes needed to pass a proposal',
    'mg.cancel': 'Cancel',
    'mg.joinModal.title': 'Join a Group',
    'mg.joinModal.desc': 'Enter the group code you were given by a leader.',
    'mg.joinModal.codePh': 'e.g. JKM-A3F9K2',
    'mg.joinModal.search': 'Search',
    'mg.joinModal.leader': 'Leader',
    'mg.joinModal.unassigned': 'Unassigned',
    'mg.joinModal.members': 'members',
    'mg.joinModal.open': 'Open — you\'ll join immediately',
    'mg.joinModal.needsApproval': 'Needs leader approval',
    'mg.joinModal.messageLabel': 'Message to the leader (optional)',
    'mg.joinModal.messagePh': 'Explain why you\'d like to join...',
    'mg.joinModal.joinNow': 'Join Now',
    'mg.joinModal.sendReq': 'Send Request',
    'mg.joinModal.joining': 'Joining...',
    'grp.copy': 'Copy',
    'grp.copied': 'Copied!',
    'grp.newProposal': '+ Proposal',
    'grp.treasury.balance': 'Treasury Balance',
    'grp.treasury.balanceDesc': 'Group funds controlled by approved proposals',
    'grp.stat.members': 'Members',
    'grp.stat.monthly': 'Monthly/Contribution',
    'grp.stat.contribution': 'Contribution',
    'grp.stat.collected': 'Total Collected',
    'grp.stat.paidThisMonth': 'Paid This Month',
    'grp.stat.thisMonth': 'This Month',
    'grp.stat.disbursed': 'Total Disbursed',
    'grp.treasury.title': 'Group Treasury',
    'grp.treasury.subtitle': 'Group funds controlled by proposals.',
    'grp.refresh': 'Refresh',
    'grp.recentActivity': 'Recent Activity',
    'grp.noActivity': 'No activity yet',
    'grp.treasuryNotOpen': 'Treasury not opened yet',
    'grp.recentProposals': 'Recent Proposals',
    'grp.viewAll': 'View all',
    'grp.groupWord': 'Group',
    'grp.ptype.general': 'General',
    'grp.ptype.ask': 'Request',
    'grp.ptype.spend': 'Spending',
    'grp.noMembers': 'No members yet',
    'grp.noMembersDesc': 'Members will appear here after joining',
    'grp.noLeadership': 'No leadership yet',
    'grp.sendToMember': 'Send Money to Member',
    'grp.sendDesc': 'Send money directly via mobile money.',
    'grp.recipientName': 'Recipient Name',
    'grp.phone': 'Phone Number',
    'grp.send': 'Send Money',
    'grp.noPayments': 'No payments yet',
    'grp.noProposals': 'No proposals yet',
    'grp.leadersCanPropose': 'Leaders can create proposals',
    'grp.newProposalTitle': 'New Proposal',
    'grp.propTitle': 'Proposal Title',
    'grp.recipientPhone': 'Recipient Phone',
    'grp.vendorName': 'Vendor Name',
    'grp.projectDuration': 'Project Duration',
    'grp.propDescPh': 'Describe your proposal in more detail...',
    'grp.projectDesc': 'Project Description',
    'grp.createProposal': 'Create Proposal',
    'grp.depositToWallet': 'Deposit to Wallet',
    'grp.ussdHint': "You'll receive a USSD prompt on your phone. Enter your PIN to confirm.",
    'grp.dontClose': "Don't close this page until payment completes.",
    'grp.invalidPhone': 'Enter a valid phone number',
    'grp.sending': 'Sending...',
    'grp.creating': 'Creating...',
    'grp.payContribution': 'Pay Contribution',
    'grp.regularContribution': 'Regular contribution',
    'grp.perMonth': 'month',
    'grp.proposals': 'Proposals',
    'grp.proposalsWord': 'proposals',
    'grp.newProposalBtn': 'New Proposal',
    'grp.clickToStart': 'Click "New Proposal" to start',
    'grp.target': 'Target',
    'grp.statusOpen': 'Open',
    'grp.statusClosed': 'Closed',
    'grp.by': 'by',

    // Wallet
    'wal.balance': 'Wallet Balance',
    'wal.deposit': 'Deposit',
    'wal.withdraw': 'Withdraw',
    'wal.transfer': 'Transfer',
    'wal.transferFull': 'Transfer Money',
    'wal.history': 'Transaction History',
    'wal.noTx': 'No transactions yet',
    'wal.sending': 'Sending...',
    'wal.amount': 'Amount (TSh)',
    'wal.phone': 'Phone Number',
    'wal.username': 'Member Username',
    'wal.usernameHint': 'Enter the member username (lowercase, numbers, and _ only)',
    'wal.success': 'Success!',
    'wal.type': 'Type',
    'wal.contribution': 'Group Contribution',
    'wal.p2p': 'Send to Member',
    'wal.chooseGroup': 'Choose Group',
    'wal.loading': 'Loading...',
    'wal.noGroups': "You're not in any group",
    'wal.recipientUsername': 'Recipient Username',
    'wal.chooseGroupPh': '-- Choose group --',
    'wal.amountTzs': 'Amount (TZS)',
    'wal.phoneShort': 'Phone Number',

    // Settings
    'set.username.title': 'Money Transfer Username',
    'set.username.hasDesc': 'Others can send you money using your username',
    'set.username.noDesc': 'Set your username so others can easily send you money',
    'set.username.yours': 'Your username',
    'set.username.checking': 'Checking...',
    'set.username.available': '✓ Available',
    'set.username.taken': '✗ Taken',
    'set.username.hint': 'Lowercase letters, numbers, and _ only (3-30 characters)',
    'set.username.saved': '✓ Saved!',
    'set.username.saving': 'Saving...',
    'set.username.save': 'Save Username',
    'set.menu.account': 'Account Information',
    'set.menu.account.desc': 'Name, phone number, email',
    'set.menu.security': 'Security',
    'set.menu.security.desc': 'Password and verification',
    'set.menu.notifications': 'Notifications',
    'set.menu.notifications.desc': 'Notification settings',
    'set.menu.language': 'Language',
    'set.comingSoon': 'Coming soon',

    // Notifications
    'notif.title': 'Notifications',
    'notif.markAllRead': 'Mark all read',
    'notif.viewAll': 'View all',
    'notif.empty': 'No notifications yet',
    'notif.emptyDesc': 'Alerts for transactions, groups and proposals will appear here.',
    'notif.all': 'All',
    'notif.unread': 'Unread',
    'notif.enablePush': 'Enable push notifications',
    'notif.pushEnabled': 'Push notifications enabled',
    'notif.pushDenied': 'Notifications blocked. Allow them in your browser settings.',
    'notif.pushUnsupported': 'This device does not support push notifications.',
    'notif.justNow': 'Just now',
    'notif.minAgo': 'min',
    'notif.hourAgo': 'h',
    'notif.dayAgo': 'd',

    // Proposal detail
    'prop.type.general': 'General',
    'prop.type.ask': 'Ask',
    'prop.type.spend': 'Spend',
    'prop.type.prodcast': 'Prodcast',
    'prop.type.general.desc': 'Regular discussion and voting — no funds involved.',
    'prop.type.ask.desc': 'Request funds from the group treasury for your business.',
    'prop.type.spend.desc': 'Shared group expense — for a vendor or service.',
    'prop.type.prodcast.desc': 'Promote a project to investors via the investment portal.',
    'prop.title.ph.general': 'e.g. Raise the monthly contribution',
    'prop.title.ph.ask': 'e.g. Business working-capital loan',
    'prop.title.ph.spend': 'e.g. Training workshop fee',
    'prop.title.ph.prodcast': 'e.g. Irrigation farming project',
    'prop.amount': 'Amount (TSH)',
    'prop.amount.ph': 'e.g. 500000',
    'prop.recipientPhone.ph': 'e.g. 0712345678',
    'prop.vendorName.ph': 'e.g. Supplies shop',
    'prop.expenseCategory': 'Expense Category',
    'prop.expenseCategory.ph': 'e.g. Supplies, Training, Event...',
    'prop.fundingGoal': 'Funding Goal (TSH)',
    'prop.fundingGoal.ph': 'e.g. 5000000',
    'prop.timeline.ph': 'e.g. 6 months',
    'prop.impact': 'Expected Impact',
    'prop.impact.ph': 'e.g. Increase revenue by 30%',
    'prop.desc.label': 'Description',
    'prop.desc.optional': '(optional)',
    'prop.projectDesc.ph': 'Describe your project to investors...',
    'prop.info.general': 'All group members will be able to vote once the proposal is created.',
    'prop.info.ask': 'Funds will be transferred directly to your wallet once the vote passes.',
    'prop.info.spend': 'All group members will be able to vote once the proposal is created.',
    'prop.info.prodcast': 'Once the vote passes, the project appears to investors on the portal.',
    'prop.cancel': 'Cancel',
    'prop.attachment': 'Attachment (photo/file)',
    'prop.attachment.add': 'Upload a photo or PDF',
    'prop.attachment.helper': 'A photo or PDF up to 2MB — e.g. a receipt, price quote, or project photo.',
    'prop.attachment.err': 'Unsupported or too-large file.',
    'prop.attachment.view': 'Open attachment',
    'prop.err.titleRequired': 'A proposal title is required.',
    'prop.err.amountInvalid': 'Enter a valid amount.',
    'prop.err.phoneRequired': "Enter the recipient's phone number.",
    'prop.err.goalInvalid': 'Enter a funding goal.',
    'prop.err.createFailed': 'Failed to create the proposal.',
    'prop.err.genericFailed': 'Something went wrong.',
    'prop.success.created': 'Proposal created!',
    'prop.backToGroup': 'Back to Group',
    'prop.by': 'by',
    'prop.open': 'Open',
    'prop.closed': 'Closed',
    'prop.abstain': 'Abstain',
    'prop.totalVotes': 'Total',
    'prop.votes': 'votes',
    'prop.needed': 'needed',
    'prop.yourVote': 'Your vote',
    'prop.recipient': 'Recipient',
    'prop.recipientPhone': "Recipient's phone",
    'prop.status.paid': 'Paid',
    'prop.status.pending': 'Pending',
    'prop.leaderAction': 'Leadership Action',
    'prop.status': 'Status',
    'prop.amountPh': 'e.g. 5000',
    'prop.chooseMember': 'Choose a member',
    'prop.notEnoughVotes': 'The proposal did not get enough votes',
    'prop.notEnoughVotesTail': 'You can reopen the vote or create a new proposal.',
    'prop.detailsHeading': 'Proposal Details',
    'prop.field.fundingGoal': 'Funding Goal',
    'prop.field.timeline': 'Timeline',
    'prop.field.impact': 'Expected Impact',
    'prop.field.projectDesc': 'Project Description',
    'prop.field.vendor': 'Vendor',
    'prop.field.expenseCategory': 'Expense Category',
    'prop.field.businessPurpose': 'Business Purpose',
    'prop.type.pillGeneral': 'General',
    'prop.type.pillAsk': 'Funding Request',
    'prop.type.pillSpend': 'Expense',
    'prop.type.pillProdcast': 'Prodcast (Investor)',
    'prop.results': 'Voting Results',
    'prop.yes': 'Yes',
    'prop.no': 'No',
    'prop.vote': 'Cast Vote',
    'prop.votingClosed': 'Voting is closed',
    'prop.canChange': 'You can change your vote at any time.',
    'prop.allCanVote': 'All group members can vote.',
    'prop.amountRequested': 'Amount Requested',
    'prop.paymentStatus': 'Payment Status',
    'prop.pending': 'Pending',
    'prop.passed': 'Proposal passed ✓ — you can pay from the group treasury.',
    'prop.amountTzs': 'Amount (TZS)',
    'prop.executing': 'Executing...',
    'prop.disburse': 'Execute Payment (Disburse)',
    'prop.fromTreasury': 'It will be paid from the group treasury balance.',
    'prop.reopenVoting': 'Re-open voting',
    'prop.err.notAllowed': 'You are not allowed to view this proposal.',
    'prop.err.loadFailed': 'Failed to load proposal.',
    'prop.err.voteFailed': 'Failed to cast vote.',
    'prop.err.invalidAmount': 'Enter a valid payment amount.',
    'prop.err.payFailed': 'Failed to execute payment.',
    'prop.err.reopenFailed': 'Failed to re-open voting.',
    'prop.reopenSuccess': 'Voting re-opened. Members can now vote.',
    'prop.chooseRecipient': 'Choose a recipient.',
    'prop.paid': 'Payment complete! (Funds disbursed)',

    // Share group
    'share.button': 'Share',
    'share.title': 'Share Group',
    'share.desc': 'Invite others to join your group',
    'share.copy': 'Copy Link',
    'share.copied': 'Copied!',
    'share.more': 'More',
    'share.msgJoin': 'Join the group',
    'share.msgCode': 'Use group code',
    'share.msgOn': 'on WashikaDAU',

    // Contribution frequency
    'grp.freq.label': 'Contribution Frequency',
    'grp.freq.monthly': 'Monthly',
    'grp.freq.weekly': 'Weekly',
    'grp.freq.contribAmount': 'Contribution',
    'grp.settings.title': 'Group Settings',
    'grp.settings.save': 'Save Changes',
    'grp.settings.saving': 'Saving...',
    'grp.settings.saved': 'Settings saved!',
    'grp.settings.leadershipOnly': 'Only leadership can change settings.',

    // Investor portal
    'inv.nav.overview': 'Overview',
    'inv.nav.projects': 'Projects',
    'inv.nav.groups': 'Groups',
    'inv.nav.wallet': 'Wallet',
    'inv.nav.profile': 'Profile',
    'inv.investorPortal': 'Investor Portal',
    'inv.publicPage': 'Public Page',
    'inv.signOut': 'Sign Out',
    'inv.contact': 'Contact',
    'inv.welcome': 'Welcome',
    'inv.overviewSub': 'Here is an overview of investment opportunities across the WashikaDAU network.',
    'inv.stat.activeProjects': 'Active Projects',
    'inv.stat.approvedProdcasts': 'Approved Prodcasts',
    'inv.stat.fundingSought': 'Funding Sought',
    'inv.stat.totalRequested': 'Total requested',
    'inv.stat.groups': 'Groups',
    'inv.stat.active': 'Active',
    'inv.stat.members': 'Members',
    'inv.stat.regions': 'regions',
    'inv.recentlyVoted': 'Recently Voted Projects',
    'inv.viewAll': 'View all',
    'inv.activeGroups': 'Active Groups',
    'inv.investmentProjects': 'Investment Projects',
    'inv.approvedByVote': 'projects approved by member vote',
    'inv.noProjects': 'No projects yet',
    'inv.noData': 'No data yet',
    'inv.wallet.title': 'nTZS Wallet',
    'inv.wallet.sub': 'Deposit, withdraw, or transfer funds via the Base network.',
    'inv.wallet.balance': 'Wallet Balance',
    'inv.deposit': 'Deposit',
    'inv.withdraw': 'Withdraw',
    'inv.recentTx': 'Recent Transactions',
    'inv.noTx': 'No transactions yet',
    'inv.profile.title': 'Your Profile',
    'inv.profile.sub': 'Your investor information',
    'inv.edit': 'Edit',
    'inv.verified': 'Account Verified',
    'inv.pending': 'Pending Verification',
    'inv.pendingSub': 'Our team will reach out within 2 business days',
    'inv.field.fullName': 'Full Name',
    'inv.field.email': 'Email',
    'inv.field.company': 'Company',
    'inv.field.country': 'Country',
    'inv.field.type': 'Type',
    'inv.field.minInvestment': 'Min Investment',
    'inv.field.maxInvestment': 'Max Investment',
    'inv.fund': 'Fund',
    'inv.seekingVote': 'Seeking Vote',
    'inv.communityApproved': 'Community Approved',
    'inv.awaitingApproval': 'Awaiting community approval',
    'inv.communityVote': 'Community vote',
    'inv.contribution': 'Contribution',
    'inv.about': 'About the project',
    'inv.expectedImpact': 'Expected impact',
    'inv.noDataSub': 'Prodcast projects will appear here once approved by groups',
    'inv.noProjectsSub': 'Groups will submit projects here through the voting process',
    'inv.approvedByVote2': 'approved by member vote',
    'inv.col.group': 'Group',
    'inv.col.members': 'Members',
    'inv.col.contribution': 'Monthly Contribution',
    'inv.col.projects': 'Projects',
    'inv.fundingGoal': 'Funding goal',
    'inv.timeline': 'Timeline',
    'inv.backToProjects': 'Back to projects',
    'inv.members': 'members',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('sw');

  // Restore the saved language on mount
  useEffect(() => {
    const saved = typeof window !== 'undefined' ? window.localStorage.getItem('wd-lang') : null;
    if (saved === 'en' || saved === 'sw') setLanguage(saved);
  }, []);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const next = prev === 'sw' ? 'en' : 'sw';
      if (typeof window !== 'undefined') window.localStorage.setItem('wd-lang', next);
      return next;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['sw']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
