'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'sw' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  sw: {
    // Header
    'nav.home': 'Nyumbani',
    'nav.about': 'Kuhusu',
    'nav.how_it_works': 'Jinsi Inavyofanya Kazi',
    'nav.impact': 'Athari',
    'nav.join': 'Jiunge',
    'nav.investor': 'Wekeza',
    'nav.login': 'Ingia',
    
    // Hero Section
    'hero.title': 'Washika DAU – Kuunganisha Wajasiriamali na Ustawi wa Jamii',
    'hero.subtitle': 'Akiba. Mafunzo. Uwekezaji. Kila kitu unachohitaji kukua kiuchumi — katika jamii moja iliyounganishwa.',
    'hero.cta.entrepreneur': 'Jisajili Sasa',
    'hero.cta.investor': 'Shirikiana Nasi',
    'hero.learn_more': 'Jifunze',
    
    // About Section
    'about.title': 'Kuhusu Washika DAU',
    'about.vision.title': 'Maono',
    'about.vision.text': 'Kuwa kitovu cha maendeleo ya kijamii na kiuchumi kinacholenga kujenga uchumi wa mzunguko endelevu.',
    'about.mission.title': 'Dhamira',
    'about.mission.text': 'Kuwawezesha wajasiriamali wadogo kupitia mafunzo, mtandao, na uongozi wa kiuchumi.',
    'about.values.title': 'Maadili',
    'about.values.text': 'Uwazi, Ushirikiano, Uongozi, na Maendeleo Endelevu.',
    
    // How It Works
    'how_it_works.title': 'Jinsi Washika DAU Inavyofanya Kazi',
    'how_it_works.step1.title': 'Uanachama na Mafunzo',
    'how_it_works.step1.text': 'Wajasiriamali wanajiunga kupitia vikundi, kulipa ada ndogo ya kila mwezi, na kupata mafunzo.',
    'how_it_works.step2.title': 'Uwekezaji wa Mtaji',
    'how_it_works.step2.text': 'Washika DAU inawekeza katika vikundi, hisa ya 30% ya uongozi.',
    'how_it_works.step3.title': 'Uchumi wa Mzunguko',
    'how_it_works.step3.text': 'Rasilimali zinazunguka ndani ya mtandao.',
    'how_it_works.step4.title': 'Ustawi wa Pamoja',
    'how_it_works.step4.text': 'Faida na mgao wa faida vinashirikiwa.',
    
    // Impact
    'impact.title': 'Athari Yetu',
    'impact.groups': 'Vikundi',
    'impact.cbts': 'CBTs',
    'impact.businesses': 'Biashara',
    'impact.growing': 'Mtandao Unaokua',
    
    // Registration
    'registration.title': 'Jisajili kwa Washika DAU',
    'registration.name': 'Jina Kamili',
    'registration.contact': 'Mawasiliano (Simu/Barua pepe)',
    'registration.location': 'Mahali',
    'registration.business_type': 'Aina ya Biashara',
    'registration.group_name': 'Jina la Kundi (ikiwa tayari uko katika kimoja)',
    'registration.gender': 'Jinsia',
    'registration.age': 'Umri',
    'registration.submit': 'Wasilisha',
    
    // Investor Section
    'investor.title': 'Kwa Nini Uwekeze na Washika DAU?',
    'investor.subtitle': 'Mfumo wa hisa ya 30%, uongozi wa kijamii, athari endelevu.',
    'investor.cta': 'Pakua Hati za Mwekezaji',
    'investor.eyebrow': 'Wekeza',
    'investor.intro': 'Tunashirikiana na wawekezaji ambao wanaelewa kwamba ukuaji wa kweli unaanzia katika jamii.',
    'investor.card1.title': 'Mfumo wa Hisa',
    'investor.card1.text': 'Unapowekeza katika kundi la Washika DAU, unapata hisa ya moja kwa moja ndani ya biashara zao. Mapato yanashirikiwa kwa uwazi kulingana na mikataba iliyowekwa wazi.',
    'investor.card2.title': 'Ufuatiliaji wa Wakati Halisi',
    'investor.card2.text': 'Kila muamala, malipo, na mkutano wa kundi unaweza kuonekana kupitia dashibodi yetu. Uwazi kamili — hakuna siri.',
    'investor.card3.title': 'Athari ya Kijamii',
    'investor.card3.text': 'Uwekezaji wako unasaidia wajasiriamali wadogo kupata mtaji, mafunzo, na mtandao wa kuwaendeleza biashara zao.',
    'investor.contact': 'Wasiliana nasi',

    // Hero extras
    'hero.motto': 'Pamoja Tunajengana',
    'hero.cta.join': 'Jiunge Sasa',
    'hero.stat.groups': 'Vikundi',
    'hero.stat.businesses': 'Biashara',
    'hero.stat.trainers': 'Wakufunzi',
    'hero.stat.trainings': 'Mafunzo',
    'hero.stat.volume': 'Kiasi kilichopita',
    'hero.stat.held': 'Kwenye vikundi',
    'hero.stat.liveNote': 'Takwimu halisi kutoka jukwaani',
    'hero.node.save': 'Weka Akiba',
    'hero.node.learn': 'Jifunze',
    'hero.node.invest': 'Wekeza',
    'hero.node.center': 'Jamii',
    'hero.live': 'Moja kwa moja',
    'hero.ticker.1': 'Asha ameweka akiba TSh 50,000',
    'hero.ticker.2': 'Kikundi THE BOYS FC kimefadhili mradi',
    'hero.ticker.3': 'Juma amekamilisha mafunzo ya biashara',
    'hero.ticker.4': 'Mwekezaji ameunga mkono kikundi kipya',

    // About / process rail
    'about.eyebrow': 'Mchakato Wetu',
    'about.heading': 'Washika DAU mfumo wa vikundi kidijitali',
    'about.subheading': 'Fuata hatua hizi nne za kimsingi kujiunge na jamii yetu ya wajasiriamali',

    // Join CTA
    'join.eyebrow': 'Jiunge',
    'join.title': 'Jiunge na sisi Leo',

    // Login page
    'login.welcome.l1': 'Karibu tena',
    'login.welcome.l2': 'kwenye jamii yako',
    'login.welcome.sub': 'Ingia kuendelea na safari yako ya biashara, mafunzo, na uwekezaji pamoja na wenzako.',
    'login.feature1': 'Fuatilia uwekezaji wako',
    'login.feature2': 'Endelea na masomo na vyeti',
    'login.feature3': 'Shirikiana na kundi lako',
    'login.heading': 'Ingia',
    'login.no_account': 'Bado huna akaunti?',
    'login.register_here': 'Jisajili hapa',
    'login.field.identifier': 'Barua pepe au nambari ya simu',
    'login.ph.identifier': '07xx xxx xxx au email@example.com',
    'login.field.password': 'Nywila',
    'login.ph.password': 'Weka nywila yako',
    'login.forgot': 'Umesahau?',
    'login.remember': 'Nikumbuke kwenye kifaa hiki',
    'login.submit': 'Ingia',
    'login.submitting': 'Inaingia...',

    // Register page
    'register.welcome.l1': 'Jiunge na jamii',
    'register.welcome.l2': 'ya wajasiriamali',
    'register.welcome.sub': 'Sajili leo na uanze safari yako ya biashara, mafunzo, na uwekezaji pamoja na wenzako.',
    'register.feature1': 'Mafunzo ya biashara na vyeti',
    'register.feature2': 'Vikundi vya akiba na uwekezaji',
    'register.feature3': 'Malipo ya M-Pesa yaliyosalimishwa',
    'register.feature4': 'Fuatilia ukuaji wa biashara yako',
    'register.heading': 'Unda Akaunti',
    'register.have_account': 'Una akaunti tayari?',
    'register.login_here': 'Ingia hapa',
    'register.section.personal': 'Taarifa za Kibinafsi',
    'register.section.business': 'Biashara na Kitambulisho',
    'register.section.password': 'Unda Nywila',
    'register.f.fullname': 'Jina Kamili',
    'register.ph.fullname': 'Jina lako kamili',
    'register.f.phone': 'Nambari ya Simu',
    'register.f.email': 'Barua Pepe',
    'register.optional': '(si lazima)',
    'register.f.location': 'Mji / Mkoa',
    'register.f.gender': 'Jinsia',
    'register.opt.select_gender': 'Chagua jinsia',
    'register.gender.female': 'Mwanamke',
    'register.gender.male': 'Mwanamume',
    'register.f.age': 'Umri',
    'register.ph.age': 'Umri wako',
    'register.f.business': 'Aina ya Biashara',
    'register.opt.select_type': 'Chagua aina',
    'register.biz.agriculture': 'Kilimo',
    'register.biz.livestock': 'Ufugaji',
    'register.biz.small': 'Biashara Ndogo',
    'register.biz.arts': 'Sanaa na Ubunifu',
    'register.biz.services': 'Huduma',
    'register.biz.tech': 'Teknolojia',
    'register.biz.other': 'Nyingine',
    'register.f.idtype': 'Aina ya Kitambulisho',
    'register.id.national': 'Kitambulisho cha Taifa',
    'register.id.voter': 'Kitambulisho cha Mpiga Kura',
    'register.id.passport': 'Paspoti',
    'register.f.idnumber': 'Nambari ya Kitambulisho',
    'register.ph.idnumber': 'Ingiza nambari ya kitambulisho',
    'register.f.password': 'Nywila',
    'register.ph.password': 'Nywila yenye nguvu',
    'register.f.confirm': 'Thibitisha Nywila',
    'register.ph.confirm': 'Rudia nywila',
    'register.submit': 'Unda Akaunti',
    'register.submitting': 'Inasajili...',
    'register.terms': 'Kwa kusajili, unakubali masharti na sera ya faragha ya Washika DAU.',
    'register.err.mismatch': 'Nywila hazifanani',
    'register.success.title': 'Umefanikiwa!',
    'register.success.text': 'Akaunti yako imeundwa. Unaweza sasa kuingia kwenye jukwaa.',
    'register.success.cta': 'Ingia Sasa',
    'register.register_another': 'Sajili mtu mwingine',

    // Common
    'common.platform': 'Jukumu Platform',
    'tagline': 'Jukwaa la Wajasiriamali Tanzania',

    // Member dashboard — navigation
    'dash.nav.overview': 'Muhtasari',
    'dash.nav.wallet': 'Pochi',
    'dash.nav.group': 'Kundi',
    'dash.nav.investments': 'Uwekezaji',
    'dash.nav.training': 'Mafunzo',
    'dash.nav.settings': 'Mipangilio',
    'dash.nav.more': 'Zaidi',
    'dash.logout': 'Toka',
    // Member dashboard — overview
    'dash.greeting': 'Habari',
    'dash.overview.subtitle': 'Hapa kuna muhtasari wa akaunti yako',
    'dash.balance.label': 'Salio Lako',
    'dash.action.deposit': 'Weka Pesa',
    'dash.action.withdraw': 'Toa Pesa',
    'dash.action.transfer': 'Hamisha',
    'dash.stat.membership': 'Hali ya Uanachama',
    'dash.stat.active': 'Hai',
    'dash.stat.pending': 'Inasubiri',
    'dash.stat.mygroup': 'Kundi Langu',
    'dash.stat.nogroup': 'Hujajiunga',
    'dash.stat.investment': 'Uwekezaji Wangu',
    'dash.stat.returns': 'Faida Inayotarajiwa',
    'dash.governance.title': 'Maamuzi ya Kikundi',
    'dash.governance.sub': 'Shiriki katika kupiga kura na maazimio ya kundi lako',
    'dash.activity.title': 'Shughuli za Hivi Karibuni',
    'dash.joined': 'Umejiunga na Washika DAU',
    'dash.quicknav.title': 'Nenda Haraka',
    'dash.quicknav.wallet': 'Wallet Yangu',
    'dash.quicknav.wallet.sub': 'Historia na mabadiliko ya salio',
    'dash.quicknav.group': 'Kundi Langu',
    'dash.quicknav.group.sub': 'Angalia wanachama na shughuli',
    'dash.quicknav.training': 'Mafunzo',
    'dash.quicknav.training.sub': 'Endelea na masomo',
    'dash.quicknav.investment': 'Uwekezaji',
    'dash.quicknav.investment.sub': 'Fuatilia mapato yako',
    'dash.member': 'Mwanachama',

    // Group detail — tabs & roles
    'grp.tab.overview': 'Muhtasari',
    'adm.title': 'Dashibodi ya Msimamizi',
    'adm.logout': 'Toka',
    'adm.lightMode': 'Mwanga',
    'adm.darkMode': 'Giza',
    'adm.nav.overview': 'Muhtasari',
    'adm.nav.members': 'Wanachama',
    'adm.nav.groups': 'Makundi',
    'adm.nav.requests': 'Maombi',
    'adm.nav.investments': 'Uwekezaji',
    'adm.nav.training': 'Mafunzo',
    'adm.nav.reports': 'Ripoti',
    'adm.nav.partners': 'Washirika wa API',
    'adm.nav.settings': 'Mipangilio',
    'adm.stat.members': 'Wanachama',
    'adm.stat.activeGroups': 'Makundi Hai',
    'adm.stat.investments': 'Uwekezaji',
    'adm.stat.revenue': 'Mapato',
    'adm.stat.memberBalance': 'Salio Wanachama',
    'adm.stat.groupBalance': 'Salio Makundi',
    'adm.stat.totalBalance': 'Jumla ya Salio',
    'adm.thisMonth': 'mwezi huu',
    'adm.walletsLinked': 'pochi zilizounganishwa',
    'adm.walletsChecked': 'pochi zote zimepitiwa',
    'adm.walletsFailed': 'pochi zilishindwa',
    'adm.treasury.title': 'Hazina Kuu (Master Treasury)',
    'adm.treasury.needsFunding': 'Inahitaji kufadhiliwa',
    'adm.treasury.funded': 'Imefadhiliwa',
    'adm.treasury.onChain': 'Salio la mnyororo (on-chain)',
    'adm.treasury.liabilities': 'Madeni (salio za watumiaji)',
    'adm.treasury.drift': 'Tofauti',
    'adm.treasury.shortfall': 'Hazina kuu ina pungufu — fedha bado ziko kwenye pochi za zamani. Bonyeza kuzihamisha ili kutoa pesa (withdrawals) kufanye kazi.',
    'adm.treasury.syncHelp': 'Sasisha amana zote: huchukua hali halisi kutoka nTZS na kuweka zote zilizokamilika (minted) kwenye salio la mwanachama/kikundi. Ndicho kinachotokea kila baada ya dakika 2 kiotomatiki.',
    'adm.treasury.syncing': 'Inasasisha…',
    'adm.treasury.syncNow': 'Sasisha amana zote sasa (sync)',
    'adm.treasury.sweeping': 'Inahamisha…',
    'adm.treasury.sweep': 'Hamisha fedha kwa Hazina Kuu',
    'adm.memberGrowth': 'Ukuaji wa Wanachama',
    'adm.c.save': 'Hifadhi',
    'adm.c.cancel': 'Ghairi',
    'adm.c.delete': 'Futa',
    'adm.c.edit': 'Hariri',
    'adm.c.view': 'Angalia',
    'adm.c.choose': 'Chagua...',
    'adm.c.date': 'Tarehe',
    'adm.c.status': 'Hali',
    'adm.c.actions': 'Vitendo',
    'adm.c.pending': 'Inasubiri',
    'adm.c.inactive': 'Haifanyi kazi',
    'adm.c.approved': 'Imekubaliwa',
    'adm.c.rejected': 'Imekataliwa',
    'adm.c.member': 'Mwanachama',
    'adm.c.group': 'Kundi',
    'adm.c.amount': 'Kiasi',
    'adm.c.returns': 'Mapato',
    'adm.c.role': 'Nafasi',
    'adm.c.networkErr': 'Hitilafu ya mtandao',
    'adm.c.error': 'Hitilafu imetokea',
    'adm.c.saving': 'Inahifadhi...',
    'adm.g.title': 'Usimamizi wa Makundi',
    'adm.g.newGroup': 'Anzisha Kundi Jipya',
    'adm.g.none': 'Hakuna makundi bado',
    'adm.g.details': 'Maelezo ya Kundi',
    'adm.g.membersLabel': 'Wanachama',
    'adm.g.monthly': 'Mchango/Mwezi',
    'adm.g.groupMembers': 'Wanachama wa Kundi',
    'adm.g.changeRole': 'Badilisha Nafasi',
    'adm.g.remove': 'Ondoa',
    'adm.g.noMembers': 'Hakuna wanachama bado',
    'adm.g.noProposals': 'Hakuna mapendekezo bado',
    'adm.g.walletBalance': 'Salio la Pochi',
    'adm.g.desc': 'Maelezo',
    'adm.g.noTx': 'Hakuna miamala bado',
    'adm.g.editGroup': 'Hariri Kundi',
    'adm.g.groupName': 'Jina la Kundi',
    'adm.g.chooseLeader': 'Chagua Kiongozi',
    'adm.g.founded': 'Tarehe ya Kuanzishwa',
    'adm.g.roleChanged': 'Nafasi ya uongozi imebadilishwa!',
    'adm.g.memberRemoved': 'Mwanachama ameondolewa!',
    'adm.g.groupDeleted': 'Kundi limefutwa!',
    'adm.g.groupUpdated': 'Kundi limebadilishwa kwa mafanikio!',
    'adm.g.groupCreated': 'Kundi limeanzishwa!',
    'adm.g.leader': 'Kiongozi',
    'adm.g.chooseLeaderPh': 'Chagua kiongozi',
    'adm.g.monthlyContrib': 'Mchango wa Kila Mwezi (TSH)',
    'adm.g.create': 'Anzisha',
    'adm.g.finStats': 'Takwimu za Fedha',
    'adm.g.investmentLabel': 'Uwekezaji',
    'adm.m.title': 'Usimamizi wa Wanachama',
    'adm.m.search': 'Tafuta wanachama...',
    'adm.m.allStatuses': 'Hali zote',
    'adm.m.none': 'Hakuna wanachama',
    'adm.m.addToGroup': '+ Ongeza kwenye kundi',
    'adm.m.newMember': 'Mwanachama Mpya',
    'adm.m.fullName': 'Jina Kamili',
    'adm.m.email': 'Barua Pepe',
    'adm.m.phone': 'Nambari ya Simu',
    'adm.m.location': 'Mahali',
    'adm.m.businessType': 'Aina ya Biashara',
    'adm.m.gender': 'Jinsia',
    'adm.m.age': 'Umri',
    'adm.m.female': 'Mwanamke',
    'adm.m.male': 'Mwanamume',
    'adm.m.bt.agriculture': 'Kilimo',
    'adm.m.bt.livestock': 'Ufugaji',
    'adm.m.bt.smallBiz': 'Biashara Ndogo',
    'adm.m.bt.arts': 'Sanaa',
    'adm.m.bt.services': 'Huduma',
    'adm.m.bt.tech': 'Teknolojia',
    'adm.m.bt.other': 'Nyingine',
    'adm.m.added': 'Mwanachama ameongezwa kwa mafanikio!',
    'adm.m.addedToGroup': 'Mwanachama ameongezwa kwenye kundi!',
    'adm.m.deleted': 'Mwanachama amefutwa!',
    'adm.i.title': 'Usimamizi wa Uwekezaji',
    'adm.i.totalInvested': 'Jumla ya Uwekezaji',
    'adm.i.totalReturns': 'Mapato ya Jumla',
    'adm.i.returnRate': 'Kiwango cha Mapato',
    'adm.i.newInvestment': 'Uwekezaji Mpya',
    'adm.i.chooseGroup': 'Chagua kundi',
    'adm.i.amountTsh': 'Kiasi (TSH)',
    'adm.i.equityPct': 'Asilimia ya Hisa (%)',
    'adm.i.expectedReturn': 'Mapato Yanayotarajiwa (TSH)',
    'adm.i.desc': 'Maelezo',
    'adm.i.none': 'Hakuna uwekezaji bado',
    'adm.r.title': 'Ripoti na Takwimu',
    'adm.r.monthly': 'Ripoti za Mwezi',
    'adm.r.special': 'Ripoti za Maalum',
    'adm.r.opening': 'Inafungua...',
    'adm.r.downloadPdf': 'Pakua PDF',
    'adm.r.viewPdf': 'Angalia PDF',
    'adm.r.none': 'Hakuna takwimu bado',
    'adm.r.gender': 'Takwimu za Jinsia',
    'adm.r.bizGrowth': 'Ukuaji wa Biashara',
    'adm.r.socialImpact': 'Athari za Kijamii',
    'adm.jr.title': 'Maombi ya Kujiunga',
    'adm.jr.none': 'Hakuna maombi ya kujiunga kwa sasa',
    'adm.jr.joining': 'Kujiunga na:',
    'adm.jr.message': 'Ujumbe:',
    'adm.jr.approve': 'Kubali',
    'adm.jr.reject': 'Kataa',
    'adm.jr.approving': 'Inakubali...',
    'adm.jr.rejecting': 'Inakataa...',
    'adm.jr.rejectReason': 'Sababu ya kukataa (si lazima):',
    'adm.jr.approved': 'Ombi limekubaliwa!',
    'adm.jr.rejected': 'Ombi limekataliwa',
    'adm.s.title': 'Mipangilio ya Mfumo',
    'adm.s.general': 'Mipangilio ya Jumla',
    'adm.s.equityRate': 'Kiwango cha Hisa (%)',
    'adm.s.monthlyFee': 'Ada ya Mwezi (TSH)',
    'adm.s.notifications': 'Arifa',
    'adm.s.emailNew': 'Arifa za barua pepe kwa wanachama wapya',
    'adm.s.weeklyReports': 'Ripoti za kila wiki',
    'adm.ct.title': 'Mafunzo na Elimu',
    'adm.ct.new': 'Mafunzo Mapya',
    'adm.ct.edit': 'Hariri Mafunzo',
    'adm.ct.aiDescribe': 'Elezea kozi unayotaka AI itengeneze',
    'adm.ct.aiDescribePh': 'Mfano: Jinsi ya kuanzisha na kukuza biashara ndogo Tanzania...',
    'adm.ct.level': 'Kiwango',
    'adm.ct.category': 'Kategoria',
    'adm.ct.lessonCount': 'Idadi ya Masomo',
    'adm.ct.aiPreview': '✦ Preview ya Kozi Iliyotengenezwa na AI',
    'adm.ct.saving': 'Inahifadhi...',
    'adm.ct.title2': 'Kichwa cha Habari',
    'adm.ct.chooseCategory': 'Chagua Kategoria',
    'adm.ct.shortDesc': 'Maelezo Mafupi',
    'adm.ct.fullContent': 'Maudhui Kamili',
    'adm.ct.duration': 'Muda',
    'adm.ct.courseOptions': 'Chaguo za Kozi',
    'adm.ct.certOnComplete': 'Toa Cheti cha Kukamilisha',
    'adm.ct.certNote': 'Wanachama watapata cheti baada ya kukamilisha kozi',
    'adm.ct.passThreshold': 'Kiwango cha Kupita (% ya masomo)',
    'adm.ct.saveChanges': 'Hifadhi Mabadiliko',
    'adm.ct.save': 'Hifadhi',
    'adm.ct.desc': 'Maelezo',
    'adm.ct.content': 'Maudhui',
    'adm.ct.edit2': 'Hariri',
    'adm.ct.manageLessons': 'Dhibiti Masomo',
    'adm.ct.newLesson': 'Somo Jipya',
    'adm.ct.lessonTopic': 'Mada ya Masomo',
    'adm.ct.lessonTopicPh': 'Mfano: Financial Basics — budgeting, saving...',
    'adm.ct.saveToCourse': 'Hifadhi Kwa Kozi',
    'adm.ct.editLesson': 'Hariri Somo',
    'adm.ct.lessonTitle': 'Kichwa cha Somo',
    'adm.ct.lessonDuration': 'Muda (Dakika)',
    'adm.ct.lessonContent': 'Maudhui ya Somo',
    'adm.ct.lessonContentPh': 'Andika maudhui ya somo hapa...',
    'adm.ct.preview': 'Preview',
    'adm.ct.clickNewLesson': 'Bonyeza “Somo Jipya” kuanza',
    'adm.ct.lvBeginner': 'Mwanzo',
    'adm.ct.lvIntermediate': 'Kati',
    'adm.ct.lvAdvanced': 'Juu',
    'adm.ct.cancel': 'Ghairi',
    'adm.ct.courseUpdated': 'Mafunzo yamebadilishwa kwa mafanikio!',
    'adm.ct.courseAdded': 'Mafunzo yameongezwa kwa mafanikio!',
    'adm.ct.courseDeleted': 'Mafunzo yamefutwa kwa mafanikio!',
    'adm.ct.deleteFailed': 'Imeshindwa kufuta',
    'adm.ct.deleteError': 'Hitilafu imetokea wakati wa kufuta.',
    'adm.ct.hidden': 'Mafunzo yamefichwa!',
    'adm.ct.published': 'Mafunzo yamechapishwa!',
    'adm.ct.enterTopic': 'Tafadhali andika mada ya kozi.',
    'adm.ct.enterDesc': 'Tafadhali andika maelezo ya mada.',
    'adm.ct.noLessonsToSave': 'Hakuna masomo ya kuhifadhi.',
    'adm.ct.lessonsSaved': 'Masomo yamehifadhiwa kwa mafanikio!',
    'adm.ct.lessonsError': 'Hitilafu imetokea wakati wa kutengeneza masomo.',
    'adm.ct.lessonUpdated': 'Somo limebadilishwa!',
    'adm.ct.lessonAdded': 'Somo limeongezwa!',
    'adm.ct.lessonSaveError': 'Hitilafu imetokea wakati wa kuhifadhi somo.',
    'adm.ct.lessonDeleted': 'Somo limefutwa!',
    'adm.ct.lessonDeleteError': 'Hitilafu imetokea wakati wa kufuta somo.',
    'adm.ct.previewFirst': 'Tengeneza preview kwanza.',
    'adm.ct.imageUrl': 'URL ya Picha',
    'adm.ct.noLessonsYet': 'Hakuna masomo bado',
    'adm.ct.noCoursesYet': 'Hakuna mafunzo bado',
    'adm.ct.networkErr': 'Hitilafu ya mtandao.',
    'adm.ct.errorRetry': 'Hitilafu imetokea. Jaribu tena.',
    'adm.ct.errorDot': 'Hitilafu imetokea.',
    'adm.o.treasuryLoadErr': 'Imeshindwa kupakia taarifa za hazina.',
    'adm.o.recentActivity': 'Shughuli za Hivi Karibuni',
    'adm.o.noActivity': 'Hakuna shughuli za hivi karibuni',
    'adm.o.disbursed': 'Malipo yamekamilika! (Funds disbursed)',
    'adm.o.walletLoadErr': 'Hitilafu ya mtandao wakati wa kupakia pochi',
    'grp.tab.members': 'Wanachama',
    'grp.tab.requests': 'Maombi',
    'grp.req.title': 'Maombi ya Kujiunga',
    'grp.req.sub': 'Kagua na uidhinishe wanaotaka kujiunga na kundi lako.',
    'grp.req.none': 'Hakuna maombi ya kujiunga kwa sasa.',
    'grp.req.approve': 'Idhinisha',
    'grp.req.reject': 'Kataa',
    'grp.req.approved': 'Ombi limeidhinishwa.',
    'grp.req.rejected': 'Ombi limekataliwa.',
    'grp.req.failed': 'Imeshindikana kushughulikia ombi.',
    'grp.tab.leadership': 'Uongozi',
    'grp.tab.fedha': 'Fedha',
    'grp.tab.decisions': 'Maamuzi',
    'grp.role.leader': 'Kiongozi',
    'grp.role.chairman': 'Mwenyekiti',
    'grp.role.secretary': 'Katibu',
    'grp.role.treasurer': 'Mweka Hazina',
    'grp.role.member': 'Mwanachama',
    'grp.founded': 'Ilianzishwa',
    'mg.title': 'Makundi Yangu',
    'mg.subtitle': 'Makundi unayoshiriki nayo',
    'mg.create': 'Unda Kundi',
    'mg.creating': 'Inaunda...',
    'mg.status': 'Hali',
    'mg.perMonth': 'kwa mwezi',
    'mg.perWeek': 'kwa wiki',
    'mg.tapToView': 'Gusa kuangalia kundi',
    'mg.view': 'Angalia',
    'mg.joinAnother': 'Jiunge na Kundi Jingine',
    'mg.joinCta': 'Jiunge na Kundi',
    'mg.emptyTitle': 'Bado hujajiunga na kundi lolote.',
    'mg.emptyHint': 'Pata nambari ya kundi (mfano: JKM-A3F9K2) kutoka kwa kiongozi.',
    'mg.myRequests': 'Maombi Yangu',
    'mg.month': 'mwezi',
    'mg.week': 'wiki',
    'mg.role.member': 'mwanachama',
    'mg.status.pending': 'Inasubiri',
    'mg.status.approved': 'Imeidhinishwa',
    'mg.status.rejected': 'Imekataliwa',
    'mg.createNew.title': 'Unda Kundi Jipya',
    'mg.createNew.desc': 'Utakuwa kiongozi wa kundi hili moja kwa moja.',
    'mg.field.name': 'Jina la Kundi',
    'mg.field.namePh': 'Mfano: Vikundi vya Maendeleo',
    'mg.field.logo': 'Nembo ya Kundi (si lazima)',
    'mg.field.logoUpload': 'Pakia nembo',
    'mg.field.logoHelper': 'Picha ya mraba inafaa zaidi. Itapunguzwa kiotomatiki.',
    'set.field.avatar': 'Picha ya Wasifu',
    'set.field.avatarHelper': 'Picha ya mraba inafaa zaidi. Itapunguzwa kiotomatiki.',
    'img.change': 'Badilisha',
    'img.remove': 'Ondoa',
    // ── Training / Jifunze ──
    'edu.title': 'Masomo',
    'edu.inProgress': 'Kozi Zinaendelea',
    'edu.certsEarned': 'Vyeti Vilivyopatikana',
    'edu.continue': 'Endelea Kujifunza',
    'edu.myCerts': 'Vyeti Vyangu',
    'edu.learn': 'Jifunze',
    'edu.learnSub': 'Jifunze',
    'edu.filter.allLevels': 'Kiwango chote',
    'edu.level.beginner': 'Mwanzo',
    'edu.level.intermediate': 'Wastani',
    'edu.level.advanced': 'Juu',
    'edu.filter.allLangs': 'Lugha zote',
    'edu.lang.sw': 'Kiswahili',
    'edu.lang.en': 'Kiingereza',
    'edu.empty': 'Hakuna makundi yaliyopatikana',
    'edu.err.load': 'Imeshindwa kupakia makundi',
    'edu.err.generic': 'Hitilafu imetokea',
    'edu.err.notReady': 'Sehemu ya mafunzo bado haijawekwa. Tafadhali wasiliana na msimamizi.',
    'edu.err.signIn': 'Tafadhali ingia ili kuona mafunzo.',
    'edu.retry': 'Jaribu tena',
    'edu.courses': 'kozi',
    'edu.certificate': 'Cheti',
    'edu.unit.hour': 's',
    'edu.unit.min': 'd',
    'edu.ai.assistant': 'AI Msaidizi',
    'edu.certs.none': 'Bado Huna Vyeti',
    'edu.cert.earned': 'Cheti Kimepatikana!',
    'edu.noCourses': 'Hakuna kozi bado katika kategoria hii.',
    'edu.noLessons': 'Hakuna masomo bado.',
    'edu.congrats': 'Hongera!',
    'edu.notPassed': 'Hujafaulu Bado',
    'edu.finishExamForCert': 'Kamilisha mtihani ili kupata cheti chako.',
    'edu.coursesHeading': 'Kozi',
    'edu.overallProgress': 'Maendeleo ya Jumla',
    'edu.examResults': 'Matokeo ya Mtihani',
    'edu.finalExam': 'Mtihani wa Mwisho',
    'edu.waitAMoment': 'Subiri Kidogo',
    'edu.firstAssessment': 'Tathmini ya Kwanza',
    'edu.lessonAssessment': 'Tathmini ya Somo',
    'edu.readyForFinal': 'Uko Tayari kwa Mtihani wa Mwisho!',
    'edu.err.loadCerts': 'Imeshindikana kupakia vyeti',
    'edu.err.loadExam': 'Imeshindikana kupakia mtihani',
    'edu.err.loadAssessment': 'Imeshindikana kupakia tathmini',
    'edu.err.loadFailed': 'Imeshindikana kupakia',
    'edu.err.courseNotFound': 'Kozi haijapatikana',
    'edu.err.lessonsNotFound': 'Masomo hayajapatikana',
    'edu.err.examNotFound': 'Mtihani haujapatikana',
    'edu.err.assessmentNotFound': 'Tathmini haijapatikana',
    'edu.err.noPreAssessment': 'Hakuna tathmini ya awali kwa kategoria hii.',
    'edu.err.noFinalExam': 'Mtihani wa mwisho haujapatikana kwa kategoria hii.',
    'edu.err.lessonNotSpecified': 'Somo halikutajwa.',
    'edu.back': 'Rudi',
    'edu.backToLearn': 'Rudi kwenye Jifunze',
    'edu.backToCourse': 'Rudi kwenye Kozi',
    'edu.backToCategory': 'Rudi kwenye Kategoria',
    'edu.backToLessons': 'Rudi kwenye Masomo',
    'edu.certs.noneDesc': 'Kamilisha kozi na ufaulu mtihani wa mwisho ili kupata cheti chako cha kwanza.',
    'edu.startLearning': 'Anza Kujifunza',
    'edu.close': 'Funga',
    'edu.noSkills': 'Hakuna ujuzi bado',
    'edu.noQuestions': 'Hakuna maswali',
    'edu.question': 'Swali',
    'edu.of': 'ya',
    'edu.continueBtn': 'Endelea',
    'edu.passed': 'Umefaulu!',
    'edu.score': 'Alama',
    'edu.err.rateLimit': 'Umezidi kikomo cha maswali. Jaribu tena baadaye.',
    'edu.err.retry': 'Hitilafu imetokea. Jaribu tena.',
    'minv.totalInvested': 'Jumla ya Uwekezaji',
    'minv.netReturns': 'Faida Halisi',
    'minv.returnRate': 'Kiwango cha Faida',
    'minv.empty': 'Bado huna uwekezaji wowote.',
    'minv.active': 'Inaendelea',
    'minv.pending': 'Inasubiri',
    'minv.amount': 'Kiasi',
    'minv.equity': 'Hisa',
    'minv.expectedReturn': 'Faida Inayotarajiwa',
    'prof.personalInfo': 'Taarifa Binafsi',
    'prof.businessInfo': 'Taarifa za Biashara',
    'prof.fullName': 'Jina Kamili',
    'prof.email': 'Barua Pepe',
    'prof.phone': 'Nambari ya Simu',
    'prof.location': 'Mahali Unapoishi',
    'prof.businessName': 'Jina la Biashara',
    'prof.businessType': 'Aina ya Biashara',
    'prof.monthlyRevenue': 'Mapato ya Kila Mwezi (TSh)',
    'prof.employeeCount': 'Idadi ya Wafanyakazi',
    'prof.businessDesc': 'Maelezo ya Biashara',
    'prof.member': 'Mwanachama',
    'prof.activeMember': 'Mwanachama Hai',
    'prof.pending': 'Inasubiri',
    'prof.saving': 'Inahifadhi...',
    'prof.save': 'Hifadhi',
    'prof.edit': 'Hariri',
    'prof.cancel': 'Ghairi',
    'prof.saveChanges': 'Hifadhi Mabadiliko',
    'dev.badge': 'Kwa watengenezaji',
    'dev.title': 'Jenga juu ya WashikaDAU',
    'dev.subtitle': 'REST API juu ya miundombinu ya akiba za jamii Tanzania. Soma vikundi, ona nani amelipa, fuatilia kila muamala wa nTZS, na angalia mapendekezo na kura zake.',
    'dev.cap.groups': 'Vikundi na wanachama',
    'dev.cap.groups.body': 'Orodhesha vikundi, unda vipya, na soma orodha ya wanachama na majukumu yao.',
    'dev.cap.paid': 'Nani amelipa',
    'dev.cap.paid.body': 'Daftari la michango kwa mwezi — pamoja na orodha ya ambao hawajalipa.',
    'dev.cap.money': 'Pochi na miamala',
    'dev.cap.money.body': 'Salio la nTZS na daftari kamili la fedha zinazoingia na kutoka.',
    'dev.cap.gov': 'Utawala',
    'dev.cap.gov.body': 'Mapendekezo ya vikundi pamoja na matokeo ya kura kwa wakati halisi.',
    'dev.cta.docs': 'Soma nyaraka',
    'dev.cta.key': 'Pata ufunguo',
    'mg.joinModal.notFound': 'Nambari hiyo haijapatikana.',
    'mg.joinModal.err': 'Hitilafu imetokea. Jaribu tena.',
    'mg.field.voting': 'Kiwango cha Kupiga Kura',
    'mg.field.of': 'kati ya',
    'mg.field.pass': 'kura kupita',
    'mg.field.currently': 'Sasa hivi',
    'mg.field.votesNeeded': 'kura zinahitajika kupitisha pendekezo',
    'mg.cancel': 'Ghairi',
    'mg.joinModal.title': 'Jiunge na Kundi',
    'mg.joinModal.desc': 'Ingiza nambari ya kundi uliyopewa na kiongozi.',
    'mg.joinModal.codePh': 'Mfano: JKM-A3F9K2',
    'mg.joinModal.search': 'Tafuta',
    'mg.joinModal.leader': 'Kiongozi',
    'mg.joinModal.unassigned': 'Hajapewa',
    'mg.joinModal.members': 'wanachama',
    'mg.joinModal.open': 'Wazi — utajiunga moja kwa moja',
    'mg.joinModal.needsApproval': 'Inahitaji idhini ya kiongozi',
    'mg.joinModal.messageLabel': 'Ujumbe kwa kiongozi (si lazima)',
    'mg.joinModal.messagePh': 'Eleza kwa nini ungependa kujiunga...',
    'mg.joinModal.joinNow': 'Jiunga Sasa',
    'mg.joinModal.sendReq': 'Tuma Ombi',
    'mg.joinModal.joining': 'Inajiunga...',
    'grp.copy': 'Nakili',
    'grp.copied': 'Imenakiliwa!',
    'grp.newProposal': '+ Pendekezo',
    'grp.treasury.balance': 'Salio la Hazina',
    'grp.treasury.balanceDesc': 'Fedha za kundi zinazodhibitiwa na mapendekezo yaliyoidhinishwa',
    'grp.stat.members': 'Wanachama',
    'grp.stat.monthly': 'Mchango/Mwezi',
    'grp.stat.contribution': 'Mchango',
    'grp.stat.collected': 'Jumla Iliyokusanywa',
    'grp.stat.paidThisMonth': 'Waliolipa Mwezi Huu',
    'grp.stat.thisMonth': 'Mwezi Huu',
    'grp.stat.disbursed': 'Jumla Iliyotumwa',
    'grp.treasury.title': 'Hazina ya Kundi',
    'grp.treasury.subtitle': 'Fedha za kundi zinazodhibitiwa na mapendekezo.',
    'grp.refresh': 'Onyesha upya',
    'grp.recentActivity': 'Shughuli za Hivi Karibuni',
    'grp.noActivity': 'Hakuna shughuli bado',
    'grp.treasuryNotOpen': 'Hazina haijafunguliwa bado',
    'grp.recentProposals': 'Mapendekezo ya Hivi Karibuni',
    'grp.viewAll': 'Angalia yote',
    'grp.groupWord': 'Kundi',
    'grp.ptype.general': 'Jumla',
    'grp.ptype.ask': 'Ombi',
    'grp.ptype.spend': 'Matumizi',
    'grp.noMembers': 'Hakuna wanachama bado',
    'grp.noMembersDesc': 'Wanachama wataonekana hapa baada ya kujiunga',
    'grp.noLeadership': 'Hakuna uongozi bado',
    'grp.sendToMember': 'Tuma Fedha kwa Mwanachama',
    'grp.sendDesc': 'Tuma pesa moja kwa moja kupitia mobile money.',
    'grp.recipientName': 'Jina la Mpokeaji',
    'grp.phone': 'Nambari ya Simu',
    'grp.send': 'Tuma Fedha',
    'grp.noPayments': 'Hakuna malipo bado',
    'grp.noProposals': 'Hakuna mapendekezo bado',

    // Member app shell — bottom tabs
    'tab.home': 'Nyumbani',
    'tab.group': 'Kikundi',
    'tab.contribute': 'Weka',
    'tab.governance': 'Utawala',
    'tab.me': 'Mimi',
    'me.logout': 'Ondoka',

    // Home screen
    'home.greet': 'Habari',
    'home.myAkiba': 'Akiba yangu',
    'home.since': 'tangu',
    'home.streak': 'Mfululizo',
    'home.months': 'miezi',
    'home.yield': 'Riba',
    'home.contribute': 'Weka mchango',
    'home.transferToGroup': 'Hamisha kwa kikundi',
    'home.withdraw': 'Toa fedha',
    'home.wallet': 'Pochi',
    'home.wallSub': 'Tofali moja = mchango wa mwanachama mmoja.',
    'home.thisMonth': 'Mwezi huu',
    'home.whoPaid': 'Nani amelipa',
    'home.needsVote': 'Inahitaji kura yako',
    'home.viewAll': 'Ona zote',
    'home.proposal': 'Pendekezo',
    'home.days': 'siku',
    'home.yes': 'Ndiyo',
    'home.no': 'Hapana',
    'home.pending': 'wanasubiri',
    'home.activity': 'Shughuli',
    'home.noActivity': 'Hakuna shughuli bado.',
    'home.noGroup': 'Bado hujajiunga na kikundi.',
    'home.joinGroup': 'Jiunge na kikundi',

    // Ukuta — the group wall
    'wall.title': 'Ukuta wa Kikundi',
    'wall.sub': 'Tofali moja kwa kila mwanachama kila mwezi. Dhahabu = amelipa.',
    'wall.paid': 'Amelipa',
    'wall.unpaid': 'Hajalipa',
    'wall.you': 'Wewe',
    'wall.empty': 'Hakuna wanachama bado.',
    'grp.leadersCanPropose': 'Viongozi wanaweza kuunda mapendekezo',
    'grp.newProposalTitle': 'Pendekezo Jipya',
    'grp.propTitle': 'Kichwa cha Pendekezo',
    'grp.recipientPhone': 'Simu ya Mpokeaji',
    'grp.vendorName': 'Jina la Muuzaji',
    'grp.projectDuration': 'Muda wa Mradi',
    'grp.propDescPh': 'Eleza pendekezo lako kwa undani zaidi...',
    'grp.projectDesc': 'Maelezo ya Mradi',
    'grp.createProposal': 'Unda Pendekezo',
    'grp.depositToWallet': 'Weka Fedha Mfukoni',
    'grp.ussdHint': 'Utapokea arifa ya USSD kwenye simu yako. Ingiza PIN kuthibitisha.',
    'grp.dontClose': 'Usifunge ukurasa huu hadi malipo yakamilike.',
    'grp.invalidPhone': 'Ingiza nambari sahihi ya simu',
    'grp.sending': 'Inatuma...',
    'grp.creating': 'Inaunda...',
    'grp.payContribution': 'Lipa Mchango',
    'grp.regularContribution': 'Mchango wa kawaida',
    'grp.perMonth': 'mwezi',
    'grp.proposals': 'Mapendekezo',
    'grp.proposalsWord': 'pendekezo',
    'grp.newProposalBtn': 'Pendekezo Jipya',
    'grp.clickToStart': 'Bonyeza "Pendekezo Jipya" kuanza',
    'grp.target': 'Lengo',
    'grp.statusOpen': 'Wazi',
    'grp.statusClosed': 'Imefungwa',
    'grp.by': 'na',

    // Wallet
    'wal.balance': 'Salio la Wallet',
    'wal.deposit': 'Weka Pesa',
    'wal.withdraw': 'Toa Pesa',
    'wal.transfer': 'Hamisha',
    'wal.transferFull': 'Hamisha Pesa',
    'wal.history': 'Historia ya Miamala',
    'wal.noTx': 'Hakuna miamala bado',
    'wal.sending': 'Inatuma...',
    'wal.amount': 'Kiasi (TSh)',
    'wal.phone': 'Nambari ya Simu',
    'wal.username': 'Username ya Mwanachama',
    'wal.usernameHint': 'Ingiza username ya mwanachama (herufi ndogo, nambari, na _ tu)',
    'wal.success': 'Imefanikiwa!',
    'wal.type': 'Aina',
    'wal.contribution': 'Mchango kwa Kundi',
    'wal.p2p': 'Tuma kwa Mwanachama',
    'wal.chooseGroup': 'Chagua Kundi',
    'wal.loading': 'Inapakia...',
    'wal.noGroups': 'Hujajiunga na kundi lolote',
    'wal.recipientUsername': 'Username ya Mpokezi',
    'wal.chooseGroupPh': '-- Chagua kundi --',
    'wal.amountTzs': 'Kiasi (TZS)',
    'wal.phoneShort': 'Namba ya Simu',

    // Settings
    'set.username.title': 'Username ya Uhamisho Pesa',
    'set.username.hasDesc': 'Wenzako wanaweza kukutumia pesa kwa kutumia username yako',
    'set.username.noDesc': 'Weka username yako ili wenzako waweze kukutumia pesa kwa urahisi',
    'set.username.yours': 'Username yako',
    'set.username.checking': 'Inakagua...',
    'set.username.available': '✓ Inapatikana',
    'set.username.taken': '✗ Imechukuliwa',
    'set.username.hint': 'Herufi ndogo, nambari, na _ tu (3-30 vibambo)',
    'set.username.saved': '✓ Imehifadhiwa!',
    'set.username.saving': 'Inahifadhi...',
    'set.username.save': 'Hifadhi Username',
    'set.menu.account': 'Taarifa za Akaunti',
    'set.menu.account.desc': 'Jina, nambari ya simu, barua pepe',
    'set.menu.security': 'Usalama',
    'set.menu.security.desc': 'Nywila na uthibitishaji',
    'set.menu.notifications': 'Arifa',
    'set.menu.notifications.desc': 'Mipangilio ya arifa',
    'set.menu.language': 'Lugha',
    'set.comingSoon': 'Hivi karibuni',

    // Notifications
    'notif.title': 'Arifa',
    'notif.markAllRead': 'Soma zote',
    'notif.viewAll': 'Angalia zote',
    'notif.empty': 'Hakuna arifa bado',
    'notif.emptyDesc': 'Arifa za miamala, vikundi na mapendekezo zitaonekana hapa.',
    'notif.all': 'Zote',
    'notif.unread': 'Hazijasomwa',
    'notif.enablePush': 'Washa arifa za simu',
    'notif.pushEnabled': 'Arifa za simu zimewashwa',
    'notif.pushDenied': 'Umezuia arifa. Ruhusu kwenye mipangilio ya kivinjari.',
    'notif.pushUnsupported': 'Kifaa hiki hakiungi mkono arifa za simu.',
    'notif.justNow': 'Sasa hivi',
    'notif.minAgo': 'dakika',
    'notif.hourAgo': 'saa',
    'notif.dayAgo': 'siku',

    // Proposal detail
    'prop.type.general': 'Jumla',
    'prop.type.ask': 'Ombi',
    'prop.type.spend': 'Matumizi',
    'prop.type.prodcast': 'Prodcast',
    'prop.type.general.desc': 'Majadiliano na upigaji kura wa kawaida — bila malipo.',
    'prop.type.ask.desc': 'Ombi la fedha kutoka hazina ya kundi kwa ajili ya biashara yako.',
    'prop.type.spend.desc': 'Matumizi ya pamoja ya kundi — kwa muuzaji au huduma.',
    'prop.type.prodcast.desc': 'Tangaza mradi kwa wawekezaji kupitia portal ya uwekezaji.',
    'prop.title.ph.general': 'k.m. Ongeza mchango wa kila mwezi',
    'prop.title.ph.ask': 'k.m. Mkopo wa mtaji wa biashara',
    'prop.title.ph.spend': 'k.m. Ada ya mkutano wa mafunzo',
    'prop.title.ph.prodcast': 'k.m. Mradi wa kilimo cha umwagiliaji',
    'prop.amount': 'Kiasi (TSH)',
    'prop.amount.ph': 'k.m. 500000',
    'prop.recipientPhone.ph': 'k.m. 0712345678',
    'prop.vendorName.ph': 'k.m. Duka la vifaa',
    'prop.expenseCategory': 'Aina ya Matumizi',
    'prop.expenseCategory.ph': 'k.m. Vifaa, Mafunzo, Tukio...',
    'prop.fundingGoal': 'Lengo la Fedha (TSH)',
    'prop.fundingGoal.ph': 'k.m. 5000000',
    'prop.timeline.ph': 'k.m. Miezi 6',
    'prop.impact': 'Athari Inayotarajiwa',
    'prop.impact.ph': 'k.m. Kuongeza mapato kwa 30%',
    'prop.desc.label': 'Maelezo',
    'prop.desc.optional': '(si lazima)',
    'prop.projectDesc.ph': 'Eleza mradi wako kwa wawekezaji...',
    'prop.info.general': 'Wanachama wote wa kundi wataweza kupiga kura baada ya pendekezo kuundwa.',
    'prop.info.ask': 'Fedha zitahamishwa moja kwa moja kwenye pochi yako baada ya kura kupita.',
    'prop.info.spend': 'Wanachama wote wa kundi wataweza kupiga kura baada ya pendekezo kuundwa.',
    'prop.info.prodcast': 'Baada ya kura kupita, mradi utaonekana kwa wawekezaji kwenye portal.',
    'prop.cancel': 'Ghairi',
    'prop.attachment': 'Kiambatisho (picha/faili)',
    'prop.attachment.add': 'Pakia picha au PDF',
    'prop.attachment.helper': 'Picha au PDF hadi 2MB — k.m. risiti, nukuu ya bei, au picha ya mradi.',
    'prop.attachment.err': 'Faili halikubaliki au ni kubwa mno.',
    'prop.attachment.view': 'Fungua kiambatisho',
    'prop.err.titleRequired': 'Kichwa cha pendekezo kinahitajika.',
    'prop.err.amountInvalid': 'Ingiza kiasi halali.',
    'prop.err.phoneRequired': 'Ingiza nambari ya simu ya mpokeaji.',
    'prop.err.goalInvalid': 'Ingiza lengo la fedha.',
    'prop.err.createFailed': 'Imeshindikana kuunda pendekezo.',
    'prop.err.genericFailed': 'Imeshindikana.',
    'prop.success.created': 'Pendekezo limeundwa!',
    'prop.backToGroup': 'Rudi Kwa Kundi',
    'prop.by': 'na',
    'prop.open': 'Wazi',
    'prop.closed': 'Imefungwa',
    'prop.abstain': 'Jiepushe',
    'prop.totalVotes': 'Jumla',
    'prop.votes': 'kura',
    'prop.needed': 'zinahitajika',
    'prop.yourVote': 'Kura yako',
    'prop.recipient': 'Mpokeaji',
    'prop.recipientPhone': 'Nambari ya simu ya mpokeaji',
    'prop.status.paid': 'Imelipwa',
    'prop.status.pending': 'Inasubiri',
    'prop.leaderAction': 'Kitendo cha Uongozi',
    'prop.status': 'Hali',
    'prop.amountPh': 'k.m. 5000',
    'prop.chooseMember': 'Chagua mwanachama',
    'prop.notEnoughVotes': 'Pendekezo halikupata kura za kutosha',
    'prop.notEnoughVotesTail': 'Unaweza kufungua kura tena au kutengeneza pendekezo jipya.',
    'prop.detailsHeading': 'Maelezo ya Pendekezo',
    'prop.field.fundingGoal': 'Lengo la Fedha',
    'prop.field.timeline': 'Muda',
    'prop.field.impact': 'Athari Inayotarajiwa',
    'prop.field.projectDesc': 'Maelezo ya mradi',
    'prop.field.vendor': 'Muuzaji',
    'prop.field.expenseCategory': 'Aina ya Matumizi',
    'prop.field.businessPurpose': 'Kusudi la Biashara',
    'prop.type.pillGeneral': 'Jumla',
    'prop.type.pillAsk': 'Ombi la Fedha',
    'prop.type.pillSpend': 'Matumizi',
    'prop.type.pillProdcast': 'Prodcast (Mwekezaji)',
    'prop.results': 'Matokeo ya Kura',
    'prop.yes': 'Ndio',
    'prop.no': 'Hapana',
    'prop.vote': 'Piga Kura',
    'prop.votingClosed': 'Upigaji kura umefungwa',
    'prop.canChange': 'Unaweza kubadilisha kura yako wakati wowote.',
    'prop.allCanVote': 'Wanachama wote wa kundi wanaweza kupiga kura.',
    'prop.amountRequested': 'Kiasi kilichoombwa',
    'prop.paymentStatus': 'Hali ya malipo',
    'prop.pending': 'Inasubiri',
    'prop.passed': 'Pendekezo limepita kura ✓ — unaweza kulipa kutoka hazina ya kundi.',
    'prop.amountTzs': 'Kiasi (TZS)',
    'prop.executing': 'Inatekeleza...',
    'prop.disburse': 'Tekeleza Malipo (Disburse)',
    'prop.fromTreasury': 'Itatolewa kwenye salio la hazina ya kundi.',
    'prop.reopenVoting': 'Fungua Kura Tena (Re-open voting)',
    'prop.err.notAllowed': 'Huruhusiwi kuona pendekezo hili.',
    'prop.err.loadFailed': 'Imeshindikana kupakua pendekezo.',
    'prop.err.voteFailed': 'Imeshindikana kupiga kura.',
    'prop.err.invalidAmount': 'Weka kiasi sahihi cha malipo.',
    'prop.err.payFailed': 'Imeshindikana kutekeleza malipo.',
    'prop.err.reopenFailed': 'Imeshindikana kufungua kura.',
    'prop.reopenSuccess': 'Kura zimefunguliwa tena. Wanachama wanaweza kupiga kura.',
    'prop.chooseRecipient': 'Chagua mpokeaji.',
    'prop.paid': 'Malipo yamekamilika! (Funds disbursed)',

    // Share group
    'share.button': 'Shiriki',
    'share.title': 'Shiriki Kundi',
    'share.desc': 'Waalike wenzako wajiunge na kundi lako',
    'share.copy': 'Nakili Kiungo',
    'share.copied': 'Imenakiliwa!',
    'share.more': 'Zaidi',
    'share.msgJoin': 'Jiunge na kundi',
    'share.msgCode': 'Tumia namba ya kundi',
    'share.msgOn': 'kwenye WashikaDAU',

    // Contribution frequency
    'grp.freq.label': 'Mzunguko wa Mchango',
    'grp.freq.monthly': 'Kila Mwezi',
    'grp.freq.weekly': 'Kila Wiki',
    'grp.freq.contribAmount': 'Mchango',
    'grp.settings.title': 'Mipangilio ya Kundi',
    'grp.settings.save': 'Hifadhi Mabadiliko',
    'grp.settings.saving': 'Inahifadhi...',
    'grp.settings.saved': 'Mipangilio yamehifadhiwa!',
    'grp.settings.leadershipOnly': 'Uongozi pekee unaweza kubadilisha mipangilio.',

    // Investor portal
    'inv.nav.overview': 'Muhtasari',
    'inv.nav.projects': 'Miradi',
    'inv.nav.groups': 'Vikundi',
    'inv.nav.wallet': 'Pochi',
    'inv.nav.profile': 'Wasifu',
    'inv.investorPortal': 'Lango la Wawekezaji',
    'inv.publicPage': 'Ukurasa wa Umma',
    'inv.signOut': 'Toka',
    'inv.contact': 'Wasiliana',
    'inv.welcome': 'Karibu',
    'inv.overviewSub': 'Hapa kuna muhtasari wa fursa za uwekezaji kwenye mtandao wa WashikaDAU.',
    'inv.stat.activeProjects': 'Miradi Inayoendelea',
    'inv.stat.approvedProdcasts': 'Prodcasts Zilizoidhinishwa',
    'inv.stat.fundingSought': 'Fedha Zinazohitajika',
    'inv.stat.totalRequested': 'Jumla iliyoombwa',
    'inv.stat.groups': 'Vikundi',
    'inv.stat.active': 'Hai',
    'inv.stat.members': 'Wanachama',
    'inv.stat.regions': 'mikoa',
    'inv.recentlyVoted': 'Miradi Iliyopigiwa Kura',
    'inv.viewAll': 'Angalia yote',
    'inv.activeGroups': 'Vikundi Hai',
    'inv.investmentProjects': 'Miradi ya Uwekezaji',
    'inv.approvedByVote': 'miradi iliyoidhinishwa kwa kura ya wanachama',
    'inv.noProjects': 'Hakuna miradi bado',
    'inv.noData': 'Hakuna data bado',
    'inv.wallet.title': 'Pochi ya nTZS',
    'inv.wallet.sub': 'Weka, toa, au hamisha fedha kupitia mtandao wa Base.',
    'inv.wallet.balance': 'Salio la Pochi',
    'inv.deposit': 'Weka Pesa',
    'inv.withdraw': 'Toa Pesa',
    'inv.recentTx': 'Miamala ya Hivi Karibuni',
    'inv.noTx': 'Hakuna miamala bado',
    'inv.profile.title': 'Wasifu Wako',
    'inv.profile.sub': 'Taarifa zako za mwekezaji',
    'inv.edit': 'Hariri',
    'inv.verified': 'Akaunti Imethibitishwa',
    'inv.pending': 'Inasubiri Uthibitisho',
    'inv.pendingSub': 'Timu yetu itawasiliana nawe ndani ya siku 2 za kazi',
    'inv.field.fullName': 'Jina Kamili',
    'inv.field.email': 'Barua Pepe',
    'inv.field.company': 'Kampuni',
    'inv.field.country': 'Nchi',
    'inv.field.type': 'Aina',
    'inv.field.minInvestment': 'Uwekezaji wa Chini',
    'inv.field.maxInvestment': 'Uwekezaji wa Juu',
    'inv.fund': 'Fadhili',
    'inv.seekingVote': 'Inatafuta Kura',
    'inv.communityApproved': 'Imeidhinishwa na Jamii',
    'inv.awaitingApproval': 'Inasubiri idhini ya jamii',
    'inv.communityVote': 'Kura ya Jamii',
    'inv.contribution': 'Mchango',
    'inv.about': 'Kuhusu Mradi',
    'inv.expectedImpact': 'Athari Inayotarajiwa',
    'inv.noDataSub': 'Miradi ya Prodcast itaonekana hapa mara itakapoidhinishwa na vikundi',
    'inv.noProjectsSub': 'Vikundi vitawasilisha miradi hapa kupitia mchakato wa kupiga kura',
    'inv.approvedByVote2': 'imeidhinishwa na kura za wanachama',
    'inv.col.group': 'Kikundi',
    'inv.col.members': 'Wanachama',
    'inv.col.contribution': 'Mchango wa Mwezi',
    'inv.col.projects': 'Miradi',
    'inv.fundingGoal': 'Lengo la Ufadhili',
    'inv.timeline': 'Muda',
    'inv.backToProjects': 'Rudi kwenye miradi',
    'inv.members': 'wanachama',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.how_it_works': 'How It Works',
    'nav.impact': 'Impact',
    'nav.investor': 'Invest',
    'nav.join': 'Join',
    'nav.login': 'Login',
    
    // Hero Section
    'hero.title': 'Washika DAU – Connecting Entrepreneurs with Community Prosperity',
    'hero.subtitle': 'We empower small entrepreneurs through training, networks, and economic leadership for a sustainable circular economy.',
    'hero.cta.entrepreneur': 'Register Now',
    'hero.cta.investor': 'Partner With Us',
    'hero.learn_more': 'Learn More',
    
    // About Section
    'about.title': 'About Washika DAU',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be a center for social and economic development that aims to build a sustainable circular economy.',
    'about.mission.title': 'Mission',
    'about.mission.text': 'To empower small entrepreneurs through training, networks, and economic leadership.',
    'about.values.title': 'Values',
    'about.values.text': 'Transparency, Collaboration, Leadership, and Sustainable Development.',
    
    // How It Works
    'how_it_works.title': 'How Washika DAU Works',
    'how_it_works.step1.title': 'Membership & Training',
    'how_it_works.step1.text': 'Entrepreneurs join via groups, pay small monthly fees, and receive training.',
    'how_it_works.step2.title': 'Capital Investment',
    'how_it_works.step2.text': 'Washika DAU invests in groups with a 30% equity stake.',
    'how_it_works.step3.title': 'Circular Economy',
    'how_it_works.step3.text': 'Resources circulate within the network.',
    'how_it_works.step4.title': 'Shared Prosperity',
    'how_it_works.step4.text': 'Profits and dividends are shared back.',
    
    // Impact
    'impact.title': 'Our Impact',
    'impact.groups': 'Groups',
    'impact.cbts': 'CBTs',
    'impact.businesses': 'Businesses',
    'impact.growing': 'Growing Network',
    
    // Registration
    'registration.title': 'Register with Washika DAU',
    'registration.name': 'Full Name',
    'registration.contact': 'Contact (Phone/Email)',
    'registration.location': 'Location',
    'registration.business_type': 'Business Type',
    'registration.group_name': 'Group Name (if already in one)',
    'registration.gender': 'Gender',
    'registration.age': 'Age',
    'registration.submit': 'Submit',
    
    // Investor Section
    'investor.title': 'Why Invest with Washika DAU?',
    'investor.subtitle': '30% equity model, community-driven, sustainable impact.',
    'investor.cta': 'Download Investor Deck',
    'investor.eyebrow': 'Invest',
    'investor.intro': 'We partner with investors who understand that true growth starts within the community.',
    'investor.card1.title': 'Equity Model',
    'investor.card1.text': 'When you invest in a Washika DAU group, you receive direct equity in their businesses. Returns are shared transparently based on clearly defined agreements.',
    'investor.card2.title': 'Real-time Tracking',
    'investor.card2.text': 'Every transaction, payment, and group meeting is visible through our dashboard. Full transparency — no secrets.',
    'investor.card3.title': 'Social Impact',
    'investor.card3.text': 'Your investment helps small entrepreneurs access capital, training, and a network to grow their businesses.',
    'investor.contact': 'Contact us',

    // Hero extras
    'hero.motto': 'Together We Build',
    'hero.cta.join': 'Join Now',
    'hero.stat.groups': 'Groups',
    'hero.stat.businesses': 'Businesses',
    'hero.stat.trainers': 'Trainers',
    'hero.stat.trainings': 'Trainings',
    'hero.stat.volume': 'Volume processed',
    'hero.stat.held': 'Held in groups',
    'hero.stat.liveNote': 'Live figures from the platform',
    'hero.node.save': 'Save',
    'hero.node.learn': 'Learn',
    'hero.node.invest': 'Invest',
    'hero.node.center': 'Community',
    'hero.live': 'Live',
    'hero.ticker.1': 'Asha saved TSh 50,000',
    'hero.ticker.2': 'Group THE BOYS FC funded a project',
    'hero.ticker.3': 'Juma completed business training',
    'hero.ticker.4': 'An investor backed a new group',

    // About / process rail
    'about.eyebrow': 'Our Process',
    'about.heading': 'Washika DAU — a digital groups platform',
    'about.subheading': 'Follow these four essential steps to join our community of entrepreneurs',

    // Join CTA
    'join.eyebrow': 'Join',
    'join.title': 'Join Us Today',

    // Login page
    'login.welcome.l1': 'Welcome back',
    'login.welcome.l2': 'to your community',
    'login.welcome.sub': 'Sign in to continue your journey of business, training, and investment with your peers.',
    'login.feature1': 'Track your investments',
    'login.feature2': 'Continue your courses and certificates',
    'login.feature3': 'Collaborate with your group',
    'login.heading': 'Sign In',
    'login.no_account': "Don't have an account yet?",
    'login.register_here': 'Register here',
    'login.field.identifier': 'Email or phone number',
    'login.ph.identifier': '07xx xxx xxx or email@example.com',
    'login.field.password': 'Password',
    'login.ph.password': 'Enter your password',
    'login.forgot': 'Forgot?',
    'login.remember': 'Remember me on this device',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',

    // Register page
    'register.welcome.l1': 'Join the community',
    'register.welcome.l2': 'of entrepreneurs',
    'register.welcome.sub': 'Register today and start your journey of business, training, and investment with your peers.',
    'register.feature1': 'Business training and certificates',
    'register.feature2': 'Savings and investment groups',
    'register.feature3': 'Secure M-Pesa payments',
    'register.feature4': 'Track your business growth',
    'register.heading': 'Create Account',
    'register.have_account': 'Already have an account?',
    'register.login_here': 'Sign in here',
    'register.section.personal': 'Personal Information',
    'register.section.business': 'Business & ID',
    'register.section.password': 'Create Password',
    'register.f.fullname': 'Full Name',
    'register.ph.fullname': 'Your full name',
    'register.f.phone': 'Phone Number',
    'register.f.email': 'Email',
    'register.optional': '(optional)',
    'register.f.location': 'City / Region',
    'register.f.gender': 'Gender',
    'register.opt.select_gender': 'Select gender',
    'register.gender.female': 'Female',
    'register.gender.male': 'Male',
    'register.f.age': 'Age',
    'register.ph.age': 'Your age',
    'register.f.business': 'Business Type',
    'register.opt.select_type': 'Select type',
    'register.biz.agriculture': 'Agriculture',
    'register.biz.livestock': 'Livestock',
    'register.biz.small': 'Small Business',
    'register.biz.arts': 'Arts & Crafts',
    'register.biz.services': 'Services',
    'register.biz.tech': 'Technology',
    'register.biz.other': 'Other',
    'register.f.idtype': 'ID Type',
    'register.id.national': 'National ID',
    'register.id.voter': 'Voter ID',
    'register.id.passport': 'Passport',
    'register.f.idnumber': 'ID Number',
    'register.ph.idnumber': 'Enter ID number',
    'register.f.password': 'Password',
    'register.ph.password': 'Strong password',
    'register.f.confirm': 'Confirm Password',
    'register.ph.confirm': 'Repeat password',
    'register.submit': 'Create Account',
    'register.submitting': 'Registering...',
    'register.terms': "By registering, you agree to Washika DAU's terms and privacy policy.",
    'register.err.mismatch': 'Passwords do not match',
    'register.success.title': 'Success!',
    'register.success.text': 'Your account has been created. You can now sign in to the platform.',
    'register.success.cta': 'Sign In Now',
    'register.register_another': 'Register another person',

    // Common
    'common.platform': 'Jukumu Platform',
    'tagline': 'Empowering Entrepreneurs, Building a Circular Economy.',

    // Member dashboard — navigation
    'dash.nav.overview': 'Overview',
    'dash.nav.wallet': 'Wallet',
    'dash.nav.group': 'My Group',
    'dash.nav.investments': 'Investments',
    'dash.nav.training': 'Training',
    'dash.nav.settings': 'Settings',
    'dash.nav.more': 'More',
    'dash.logout': 'Logout',
    // Member dashboard — overview
    'dash.greeting': 'Hello',
    'dash.overview.subtitle': "Here's a summary of your account",
    'dash.balance.label': 'Your Balance',
    'dash.action.deposit': 'Deposit',
    'dash.action.withdraw': 'Withdraw',
    'dash.action.transfer': 'Transfer',
    'dash.stat.membership': 'Membership Status',
    'dash.stat.active': 'Active',
    'dash.stat.pending': 'Pending',
    'dash.stat.mygroup': 'My Group',
    'dash.stat.nogroup': 'Not joined',
    'dash.stat.investment': 'My Investment',
    'dash.stat.returns': 'Expected Returns',
    'dash.governance.title': 'Group Decisions',
    'dash.governance.sub': "Take part in your group's votes and resolutions",
    'dash.activity.title': 'Recent Activity',
    'dash.joined': 'Joined Washika DAU',
    'dash.quicknav.title': 'Quick Links',
    'dash.quicknav.wallet': 'My Wallet',
    'dash.quicknav.wallet.sub': 'History and balance changes',
    'dash.quicknav.group': 'My Group',
    'dash.quicknav.group.sub': 'View members and activity',
    'dash.quicknav.training': 'Training',
    'dash.quicknav.training.sub': 'Continue your courses',
    'dash.quicknav.investment': 'Investment',
    'dash.quicknav.investment.sub': 'Track your returns',
    'dash.member': 'Member',

    // Group detail — tabs & roles
    'grp.tab.overview': 'Overview',
    'adm.title': 'Admin dashboard',
    'adm.logout': 'Sign out',
    'adm.lightMode': 'Light',
    'adm.darkMode': 'Dark',
    'adm.nav.overview': 'Overview',
    'adm.nav.members': 'Members',
    'adm.nav.groups': 'Groups',
    'adm.nav.requests': 'Requests',
    'adm.nav.investments': 'Investments',
    'adm.nav.training': 'Training',
    'adm.nav.reports': 'Reports',
    'adm.nav.partners': 'API Partners',
    'adm.nav.settings': 'Settings',
    'adm.stat.members': 'Members',
    'adm.stat.activeGroups': 'Active groups',
    'adm.stat.investments': 'Investments',
    'adm.stat.revenue': 'Revenue',
    'adm.stat.memberBalance': 'Member balances',
    'adm.stat.groupBalance': 'Group balances',
    'adm.stat.totalBalance': 'Total balance',
    'adm.thisMonth': 'this month',
    'adm.walletsLinked': 'wallets linked',
    'adm.walletsChecked': 'all wallets checked',
    'adm.walletsFailed': 'wallets failed',
    'adm.treasury.title': 'Master treasury',
    'adm.treasury.needsFunding': 'Needs funding',
    'adm.treasury.funded': 'Funded',
    'adm.treasury.onChain': 'On-chain balance',
    'adm.treasury.liabilities': 'Liabilities (user balances)',
    'adm.treasury.drift': 'Drift',
    'adm.treasury.shortfall': 'The master treasury is short — funds are still sitting in legacy wallets. Sweep them so withdrawals can work.',
    'adm.treasury.syncHelp': 'Sync all deposits: pulls the real state from nTZS and posts everything minted to the member or group balance. This runs automatically every 2 minutes.',
    'adm.treasury.syncing': 'Syncing…',
    'adm.treasury.syncNow': 'Sync all deposits now',
    'adm.treasury.sweeping': 'Sweeping…',
    'adm.treasury.sweep': 'Sweep funds to master treasury',
    'adm.memberGrowth': 'Member growth',
    'adm.c.save': 'Save',
    'adm.c.cancel': 'Cancel',
    'adm.c.delete': 'Delete',
    'adm.c.edit': 'Edit',
    'adm.c.view': 'View',
    'adm.c.choose': 'Choose...',
    'adm.c.date': 'Date',
    'adm.c.status': 'Status',
    'adm.c.actions': 'Actions',
    'adm.c.pending': 'Pending',
    'adm.c.inactive': 'Inactive',
    'adm.c.approved': 'Approved',
    'adm.c.rejected': 'Rejected',
    'adm.c.member': 'Member',
    'adm.c.group': 'Group',
    'adm.c.amount': 'Amount',
    'adm.c.returns': 'Returns',
    'adm.c.role': 'Role',
    'adm.c.networkErr': 'Network error',
    'adm.c.error': 'Something went wrong',
    'adm.c.saving': 'Saving...',
    'adm.g.title': 'Group management',
    'adm.g.newGroup': 'Create a new group',
    'adm.g.none': 'No groups yet',
    'adm.g.details': 'Group details',
    'adm.g.membersLabel': 'Members',
    'adm.g.monthly': 'Contribution/month',
    'adm.g.groupMembers': 'Group members',
    'adm.g.changeRole': 'Change role',
    'adm.g.remove': 'Remove',
    'adm.g.noMembers': 'No members yet',
    'adm.g.noProposals': 'No proposals yet',
    'adm.g.walletBalance': 'Wallet balance',
    'adm.g.desc': 'Description',
    'adm.g.noTx': 'No transactions yet',
    'adm.g.editGroup': 'Edit group',
    'adm.g.groupName': 'Group name',
    'adm.g.chooseLeader': 'Choose a leader',
    'adm.g.founded': 'Founded date',
    'adm.g.roleChanged': 'Leadership role changed!',
    'adm.g.memberRemoved': 'Member removed!',
    'adm.g.groupDeleted': 'Group deleted!',
    'adm.g.groupUpdated': 'Group updated successfully!',
    'adm.g.groupCreated': 'Group created!',
    'adm.g.leader': 'Leader',
    'adm.g.chooseLeaderPh': 'Choose a leader',
    'adm.g.monthlyContrib': 'Monthly contribution (TSH)',
    'adm.g.create': 'Create',
    'adm.g.finStats': 'Financial statistics',
    'adm.g.investmentLabel': 'Investment',
    'adm.m.title': 'Member management',
    'adm.m.search': 'Search members...',
    'adm.m.allStatuses': 'All statuses',
    'adm.m.none': 'No members',
    'adm.m.addToGroup': '+ Add to group',
    'adm.m.newMember': 'New member',
    'adm.m.fullName': 'Full name',
    'adm.m.email': 'Email',
    'adm.m.phone': 'Phone number',
    'adm.m.location': 'Location',
    'adm.m.businessType': 'Business type',
    'adm.m.gender': 'Gender',
    'adm.m.age': 'Age',
    'adm.m.female': 'Female',
    'adm.m.male': 'Male',
    'adm.m.bt.agriculture': 'Agriculture',
    'adm.m.bt.livestock': 'Livestock',
    'adm.m.bt.smallBiz': 'Small business',
    'adm.m.bt.arts': 'Arts',
    'adm.m.bt.services': 'Services',
    'adm.m.bt.tech': 'Technology',
    'adm.m.bt.other': 'Other',
    'adm.m.added': 'Member added successfully!',
    'adm.m.addedToGroup': 'Member added to the group!',
    'adm.m.deleted': 'Member deleted!',
    'adm.i.title': 'Investment management',
    'adm.i.totalInvested': 'Total invested',
    'adm.i.totalReturns': 'Total returns',
    'adm.i.returnRate': 'Return rate',
    'adm.i.newInvestment': 'New investment',
    'adm.i.chooseGroup': 'Choose a group',
    'adm.i.amountTsh': 'Amount (TSH)',
    'adm.i.equityPct': 'Equity percentage (%)',
    'adm.i.expectedReturn': 'Expected return (TSH)',
    'adm.i.desc': 'Description',
    'adm.i.none': 'No investments yet',
    'adm.r.title': 'Reports & analytics',
    'adm.r.monthly': 'Monthly reports',
    'adm.r.special': 'Special reports',
    'adm.r.opening': 'Opening...',
    'adm.r.downloadPdf': 'Download PDF',
    'adm.r.viewPdf': 'View PDF',
    'adm.r.none': 'No data yet',
    'adm.r.gender': 'Gender statistics',
    'adm.r.bizGrowth': 'Business growth',
    'adm.r.socialImpact': 'Social impact',
    'adm.jr.title': 'Join requests',
    'adm.jr.none': 'No join requests right now',
    'adm.jr.joining': 'Joining:',
    'adm.jr.message': 'Message:',
    'adm.jr.approve': 'Approve',
    'adm.jr.reject': 'Decline',
    'adm.jr.approving': 'Approving...',
    'adm.jr.rejecting': 'Declining...',
    'adm.jr.rejectReason': 'Reason for declining (optional):',
    'adm.jr.approved': 'Request approved!',
    'adm.jr.rejected': 'Request declined',
    'adm.s.title': 'System settings',
    'adm.s.general': 'General settings',
    'adm.s.equityRate': 'Equity rate (%)',
    'adm.s.monthlyFee': 'Monthly fee (TSH)',
    'adm.s.notifications': 'Notifications',
    'adm.s.emailNew': 'Email notifications for new members',
    'adm.s.weeklyReports': 'Weekly reports',
    'adm.ct.title': 'Training & education',
    'adm.ct.new': 'New course',
    'adm.ct.edit': 'Edit course',
    'adm.ct.aiDescribe': 'Describe the course you want AI to generate',
    'adm.ct.aiDescribePh': 'e.g. How to start and grow a small business in Tanzania...',
    'adm.ct.level': 'Level',
    'adm.ct.category': 'Category',
    'adm.ct.lessonCount': 'Number of lessons',
    'adm.ct.aiPreview': '✦ AI-generated course preview',
    'adm.ct.saving': 'Saving...',
    'adm.ct.title2': 'Title',
    'adm.ct.chooseCategory': 'Choose a category',
    'adm.ct.shortDesc': 'Short description',
    'adm.ct.fullContent': 'Full content',
    'adm.ct.duration': 'Duration',
    'adm.ct.courseOptions': 'Course options',
    'adm.ct.certOnComplete': 'Award a completion certificate',
    'adm.ct.certNote': 'Members receive a certificate after completing the course',
    'adm.ct.passThreshold': 'Pass threshold (% of lessons)',
    'adm.ct.saveChanges': 'Save changes',
    'adm.ct.save': 'Save',
    'adm.ct.desc': 'Description',
    'adm.ct.content': 'Content',
    'adm.ct.edit2': 'Edit',
    'adm.ct.manageLessons': 'Manage lessons',
    'adm.ct.newLesson': 'New lesson',
    'adm.ct.lessonTopic': 'Lesson topic',
    'adm.ct.lessonTopicPh': 'e.g. Financial Basics — budgeting, saving...',
    'adm.ct.saveToCourse': 'Save to course',
    'adm.ct.editLesson': 'Edit lesson',
    'adm.ct.lessonTitle': 'Lesson title',
    'adm.ct.lessonDuration': 'Duration (minutes)',
    'adm.ct.lessonContent': 'Lesson content',
    'adm.ct.lessonContentPh': 'Write the lesson content here...',
    'adm.ct.preview': 'Preview',
    'adm.ct.clickNewLesson': 'Click “New lesson” to start',
    'adm.ct.lvBeginner': 'Beginner',
    'adm.ct.lvIntermediate': 'Intermediate',
    'adm.ct.lvAdvanced': 'Advanced',
    'adm.ct.cancel': 'Cancel',
    'adm.ct.courseUpdated': 'Course updated successfully!',
    'adm.ct.courseAdded': 'Course added successfully!',
    'adm.ct.courseDeleted': 'Course deleted successfully!',
    'adm.ct.deleteFailed': 'Delete failed',
    'adm.ct.deleteError': 'Something went wrong while deleting.',
    'adm.ct.hidden': 'Course hidden!',
    'adm.ct.published': 'Course published!',
    'adm.ct.enterTopic': 'Please enter a course topic.',
    'adm.ct.enterDesc': 'Please enter a topic description.',
    'adm.ct.noLessonsToSave': 'No lessons to save.',
    'adm.ct.lessonsSaved': 'Lessons saved successfully!',
    'adm.ct.lessonsError': 'Something went wrong while generating lessons.',
    'adm.ct.lessonUpdated': 'Lesson updated!',
    'adm.ct.lessonAdded': 'Lesson added!',
    'adm.ct.lessonSaveError': 'Something went wrong while saving the lesson.',
    'adm.ct.lessonDeleted': 'Lesson deleted!',
    'adm.ct.lessonDeleteError': 'Something went wrong while deleting the lesson.',
    'adm.ct.previewFirst': 'Generate a preview first.',
    'adm.ct.imageUrl': 'Image URL',
    'adm.ct.noLessonsYet': 'No lessons yet',
    'adm.ct.noCoursesYet': 'No courses yet',
    'adm.ct.networkErr': 'Network error.',
    'adm.ct.errorRetry': 'Something went wrong. Try again.',
    'adm.ct.errorDot': 'Something went wrong.',
    'adm.o.treasuryLoadErr': 'Could not load treasury data.',
    'adm.o.recentActivity': 'Recent activity',
    'adm.o.noActivity': 'No recent activity',
    'adm.o.disbursed': 'Payment completed! (Funds disbursed)',
    'adm.o.walletLoadErr': 'Network error while loading wallets',
    'grp.tab.members': 'Members',
    'grp.tab.requests': 'Requests',
    'grp.req.title': 'Join requests',
    'grp.req.sub': 'Review and approve people asking to join your group.',
    'grp.req.none': 'No join requests right now.',
    'grp.req.approve': 'Approve',
    'grp.req.reject': 'Decline',
    'grp.req.approved': 'Request approved.',
    'grp.req.rejected': 'Request declined.',
    'grp.req.failed': 'Could not process that request.',
    'grp.tab.leadership': 'Leadership',
    'grp.tab.fedha': 'Finances',
    'grp.tab.decisions': 'Decisions',
    'grp.role.leader': 'Leader',
    'grp.role.chairman': 'Chairman',
    'grp.role.secretary': 'Secretary',
    'grp.role.treasurer': 'Treasurer',
    'grp.role.member': 'Member',
    'grp.founded': 'Founded',
    'mg.title': 'My Groups',
    'mg.subtitle': 'Groups you belong to',
    'mg.create': 'Create Group',
    'mg.creating': 'Creating...',
    'mg.status': 'Status',
    'mg.perMonth': 'per month',
    'mg.perWeek': 'per week',
    'mg.tapToView': 'Tap to view group',
    'mg.view': 'View',
    'mg.joinAnother': 'Join Another Group',
    'mg.joinCta': 'Join a Group',
    'mg.emptyTitle': "You haven't joined any group yet.",
    'mg.emptyHint': 'Get a group code (e.g. JKM-A3F9K2) from a leader.',
    'mg.myRequests': 'My Requests',
    'mg.month': 'month',
    'mg.week': 'week',
    'mg.role.member': 'member',
    'mg.status.pending': 'Pending',
    'mg.status.approved': 'Approved',
    'mg.status.rejected': 'Rejected',
    'mg.createNew.title': 'Create a New Group',
    'mg.createNew.desc': "You'll automatically become the leader of this group.",
    'mg.field.name': 'Group Name',
    'mg.field.namePh': 'e.g. Development Circle',
    'mg.field.logo': 'Group Logo (optional)',
    'mg.field.logoUpload': 'Upload logo',
    'mg.field.logoHelper': 'A square photo works best. It will be resized automatically.',
    'set.field.avatar': 'Profile Photo',
    'set.field.avatarHelper': 'A square photo works best. It will be resized automatically.',
    'img.change': 'Change',
    'img.remove': 'Remove',
    // ── Training / Jifunze ──
    'edu.title': 'Training',
    'edu.inProgress': 'Courses in progress',
    'edu.certsEarned': 'Certificates earned',
    'edu.continue': 'Continue learning',
    'edu.myCerts': 'My certificates',
    'edu.learn': 'Learn',
    'edu.learnSub': 'Learn',
    'edu.filter.allLevels': 'All levels',
    'edu.level.beginner': 'Beginner',
    'edu.level.intermediate': 'Intermediate',
    'edu.level.advanced': 'Advanced',
    'edu.filter.allLangs': 'All languages',
    'edu.lang.sw': 'Swahili',
    'edu.lang.en': 'English',
    'edu.empty': 'No categories found',
    'edu.err.load': 'Could not load categories',
    'edu.err.generic': 'Something went wrong',
    'edu.err.notReady': 'The training section is not set up yet. Please contact an administrator.',
    'edu.err.signIn': 'Please sign in to view training.',
    'edu.retry': 'Try again',
    'edu.courses': 'courses',
    'edu.certificate': 'Certificate',
    'edu.unit.hour': 'h',
    'edu.unit.min': 'm',
    'edu.ai.assistant': 'AI Assistant',
    'edu.certs.none': 'No certificates yet',
    'edu.cert.earned': 'Certificate earned!',
    'edu.noCourses': 'No courses in this category yet.',
    'edu.noLessons': 'No lessons yet.',
    'edu.congrats': 'Congratulations!',
    'edu.notPassed': 'Not passed yet',
    'edu.finishExamForCert': 'Complete the final exam to earn your certificate.',
    'edu.coursesHeading': 'Courses',
    'edu.overallProgress': 'Overall progress',
    'edu.examResults': 'Exam results',
    'edu.finalExam': 'Final exam',
    'edu.waitAMoment': 'Hold on a moment',
    'edu.firstAssessment': 'Initial assessment',
    'edu.lessonAssessment': 'Lesson assessment',
    'edu.readyForFinal': "You're ready for the final exam!",
    'edu.err.loadCerts': 'Could not load certificates',
    'edu.err.loadExam': 'Could not load the exam',
    'edu.err.loadAssessment': 'Could not load the assessment',
    'edu.err.loadFailed': 'Could not load',
    'edu.err.courseNotFound': 'Course not found',
    'edu.err.lessonsNotFound': 'Lessons not found',
    'edu.err.examNotFound': 'Exam not found',
    'edu.err.assessmentNotFound': 'Assessment not found',
    'edu.err.noPreAssessment': 'There is no initial assessment for this category.',
    'edu.err.noFinalExam': 'There is no final exam for this category.',
    'edu.err.lessonNotSpecified': 'No lesson was specified.',
    'edu.back': 'Back',
    'edu.backToLearn': 'Back to Learn',
    'edu.backToCourse': 'Back to course',
    'edu.backToCategory': 'Back to category',
    'edu.backToLessons': 'Back to lessons',
    'edu.certs.noneDesc': 'Complete a course and pass its final exam to earn your first certificate.',
    'edu.startLearning': 'Start learning',
    'edu.close': 'Close',
    'edu.noSkills': 'No skills yet',
    'edu.noQuestions': 'No questions',
    'edu.question': 'Question',
    'edu.of': 'of',
    'edu.continueBtn': 'Continue',
    'edu.passed': 'You passed!',
    'edu.score': 'Score',
    'edu.err.rateLimit': "You've hit the question limit. Try again later.",
    'edu.err.retry': 'Something went wrong. Try again.',
    'minv.totalInvested': 'Total invested',
    'minv.netReturns': 'Net returns',
    'minv.returnRate': 'Return rate',
    'minv.empty': "You don't have any investments yet.",
    'minv.active': 'Active',
    'minv.pending': 'Pending',
    'minv.amount': 'Amount',
    'minv.equity': 'Equity',
    'minv.expectedReturn': 'Expected return',
    'prof.personalInfo': 'Personal information',
    'prof.businessInfo': 'Business information',
    'prof.fullName': 'Full name',
    'prof.email': 'Email',
    'prof.phone': 'Phone number',
    'prof.location': 'Where you live',
    'prof.businessName': 'Business name',
    'prof.businessType': 'Business type',
    'prof.monthlyRevenue': 'Monthly revenue (TSh)',
    'prof.employeeCount': 'Number of employees',
    'prof.businessDesc': 'Business description',
    'prof.member': 'Member',
    'prof.activeMember': 'Active member',
    'prof.pending': 'Pending',
    'prof.saving': 'Saving...',
    'prof.save': 'Save',
    'prof.edit': 'Edit',
    'prof.cancel': 'Cancel',
    'prof.saveChanges': 'Save changes',
    'dev.badge': 'For developers',
    'dev.title': 'Build on WashikaDAU',
    'dev.subtitle': "A REST API over Tanzania's community savings infrastructure. Read groups, see exactly who has paid, follow every nTZS transaction, and track proposals with live vote tallies.",
    'dev.cap.groups': 'Groups & members',
    'dev.cap.groups.body': 'List and create groups, and read full rosters with each member\u2019s role.',
    'dev.cap.paid': 'Who paid',
    'dev.cap.paid.body': 'The contribution ledger per month \u2014 including the roster of who has not paid.',
    'dev.cap.money': 'Wallets & transactions',
    'dev.cap.money.body': 'nTZS balances and the complete ledger of money in and out.',
    'dev.cap.gov': 'Governance',
    'dev.cap.gov.body': 'Group proposals with live vote tallies and payout status.',
    'dev.cta.docs': 'Read the docs',
    'dev.cta.key': 'Get an API key',
    'mg.joinModal.notFound': 'That code was not found.',
    'mg.joinModal.err': 'Something went wrong. Try again.',
    'mg.field.voting': 'Voting Threshold',
    'mg.field.of': 'of',
    'mg.field.pass': 'votes to pass',
    'mg.field.currently': 'Currently',
    'mg.field.votesNeeded': 'votes needed to pass a proposal',
    'mg.cancel': 'Cancel',
    'mg.joinModal.title': 'Join a Group',
    'mg.joinModal.desc': 'Enter the group code you were given by a leader.',
    'mg.joinModal.codePh': 'e.g. JKM-A3F9K2',
    'mg.joinModal.search': 'Search',
    'mg.joinModal.leader': 'Leader',
    'mg.joinModal.unassigned': 'Unassigned',
    'mg.joinModal.members': 'members',
    'mg.joinModal.open': 'Open — you\'ll join immediately',
    'mg.joinModal.needsApproval': 'Needs leader approval',
    'mg.joinModal.messageLabel': 'Message to the leader (optional)',
    'mg.joinModal.messagePh': 'Explain why you\'d like to join...',
    'mg.joinModal.joinNow': 'Join Now',
    'mg.joinModal.sendReq': 'Send Request',
    'mg.joinModal.joining': 'Joining...',
    'grp.copy': 'Copy',
    'grp.copied': 'Copied!',
    'grp.newProposal': '+ Proposal',
    'grp.treasury.balance': 'Treasury Balance',
    'grp.treasury.balanceDesc': 'Group funds controlled by approved proposals',
    'grp.stat.members': 'Members',
    'grp.stat.monthly': 'Monthly/Contribution',
    'grp.stat.contribution': 'Contribution',
    'grp.stat.collected': 'Total Collected',
    'grp.stat.paidThisMonth': 'Paid This Month',
    'grp.stat.thisMonth': 'This Month',
    'grp.stat.disbursed': 'Total Disbursed',
    'grp.treasury.title': 'Group Treasury',
    'grp.treasury.subtitle': 'Group funds controlled by proposals.',
    'grp.refresh': 'Refresh',
    'grp.recentActivity': 'Recent Activity',
    'grp.noActivity': 'No activity yet',
    'grp.treasuryNotOpen': 'Treasury not opened yet',
    'grp.recentProposals': 'Recent Proposals',
    'grp.viewAll': 'View all',
    'grp.groupWord': 'Group',
    'grp.ptype.general': 'General',
    'grp.ptype.ask': 'Request',
    'grp.ptype.spend': 'Spending',
    'grp.noMembers': 'No members yet',
    'grp.noMembersDesc': 'Members will appear here after joining',
    'grp.noLeadership': 'No leadership yet',
    'grp.sendToMember': 'Send Money to Member',
    'grp.sendDesc': 'Send money directly via mobile money.',
    'grp.recipientName': 'Recipient Name',
    'grp.phone': 'Phone Number',
    'grp.send': 'Send Money',
    'grp.noPayments': 'No payments yet',
    'grp.noProposals': 'No proposals yet',

    // Member app shell — bottom tabs
    'tab.home': 'Home',
    'tab.group': 'Group',
    'tab.contribute': 'Add',
    'tab.governance': 'Govern',
    'tab.me': 'Me',
    'me.logout': 'Log out',

    // Home screen
    'home.greet': 'Hello',
    'home.myAkiba': 'My savings',
    'home.since': 'since',
    'home.streak': 'Streak',
    'home.months': 'months',
    'home.yield': 'Yield',
    'home.contribute': 'Make contribution',
    'home.transferToGroup': 'Transfer to group',
    'home.withdraw': 'Withdraw',
    'home.wallet': 'Wallet',
    'home.wallSub': 'One brick = one member’s contribution.',
    'home.thisMonth': 'This month',
    'home.whoPaid': 'Who has paid',
    'home.needsVote': 'Needs your vote',
    'home.viewAll': 'View all',
    'home.proposal': 'Proposal',
    'home.days': 'days',
    'home.yes': 'Yes',
    'home.no': 'No',
    'home.pending': 'pending',
    'home.activity': 'Activity',
    'home.noActivity': 'No activity yet.',
    'home.noGroup': 'You haven’t joined a group yet.',
    'home.joinGroup': 'Join a group',

    // Ukuta — the group wall
    'wall.title': 'The Group Wall',
    'wall.sub': 'One brick per member per month. Gold means paid.',
    'wall.paid': 'Paid',
    'wall.unpaid': 'Unpaid',
    'wall.you': 'You',
    'wall.empty': 'No members yet.',
    'grp.leadersCanPropose': 'Leaders can create proposals',
    'grp.newProposalTitle': 'New Proposal',
    'grp.propTitle': 'Proposal Title',
    'grp.recipientPhone': 'Recipient Phone',
    'grp.vendorName': 'Vendor Name',
    'grp.projectDuration': 'Project Duration',
    'grp.propDescPh': 'Describe your proposal in more detail...',
    'grp.projectDesc': 'Project Description',
    'grp.createProposal': 'Create Proposal',
    'grp.depositToWallet': 'Deposit to Wallet',
    'grp.ussdHint': "You'll receive a USSD prompt on your phone. Enter your PIN to confirm.",
    'grp.dontClose': "Don't close this page until payment completes.",
    'grp.invalidPhone': 'Enter a valid phone number',
    'grp.sending': 'Sending...',
    'grp.creating': 'Creating...',
    'grp.payContribution': 'Pay Contribution',
    'grp.regularContribution': 'Regular contribution',
    'grp.perMonth': 'month',
    'grp.proposals': 'Proposals',
    'grp.proposalsWord': 'proposals',
    'grp.newProposalBtn': 'New Proposal',
    'grp.clickToStart': 'Click "New Proposal" to start',
    'grp.target': 'Target',
    'grp.statusOpen': 'Open',
    'grp.statusClosed': 'Closed',
    'grp.by': 'by',

    // Wallet
    'wal.balance': 'Wallet Balance',
    'wal.deposit': 'Deposit',
    'wal.withdraw': 'Withdraw',
    'wal.transfer': 'Transfer',
    'wal.transferFull': 'Transfer Money',
    'wal.history': 'Transaction History',
    'wal.noTx': 'No transactions yet',
    'wal.sending': 'Sending...',
    'wal.amount': 'Amount (TSh)',
    'wal.phone': 'Phone Number',
    'wal.username': 'Member Username',
    'wal.usernameHint': 'Enter the member username (lowercase, numbers, and _ only)',
    'wal.success': 'Success!',
    'wal.type': 'Type',
    'wal.contribution': 'Group Contribution',
    'wal.p2p': 'Send to Member',
    'wal.chooseGroup': 'Choose Group',
    'wal.loading': 'Loading...',
    'wal.noGroups': "You're not in any group",
    'wal.recipientUsername': 'Recipient Username',
    'wal.chooseGroupPh': '-- Choose group --',
    'wal.amountTzs': 'Amount (TZS)',
    'wal.phoneShort': 'Phone Number',

    // Settings
    'set.username.title': 'Money Transfer Username',
    'set.username.hasDesc': 'Others can send you money using your username',
    'set.username.noDesc': 'Set your username so others can easily send you money',
    'set.username.yours': 'Your username',
    'set.username.checking': 'Checking...',
    'set.username.available': '✓ Available',
    'set.username.taken': '✗ Taken',
    'set.username.hint': 'Lowercase letters, numbers, and _ only (3-30 characters)',
    'set.username.saved': '✓ Saved!',
    'set.username.saving': 'Saving...',
    'set.username.save': 'Save Username',
    'set.menu.account': 'Account Information',
    'set.menu.account.desc': 'Name, phone number, email',
    'set.menu.security': 'Security',
    'set.menu.security.desc': 'Password and verification',
    'set.menu.notifications': 'Notifications',
    'set.menu.notifications.desc': 'Notification settings',
    'set.menu.language': 'Language',
    'set.comingSoon': 'Coming soon',

    // Notifications
    'notif.title': 'Notifications',
    'notif.markAllRead': 'Mark all read',
    'notif.viewAll': 'View all',
    'notif.empty': 'No notifications yet',
    'notif.emptyDesc': 'Alerts for transactions, groups and proposals will appear here.',
    'notif.all': 'All',
    'notif.unread': 'Unread',
    'notif.enablePush': 'Enable push notifications',
    'notif.pushEnabled': 'Push notifications enabled',
    'notif.pushDenied': 'Notifications blocked. Allow them in your browser settings.',
    'notif.pushUnsupported': 'This device does not support push notifications.',
    'notif.justNow': 'Just now',
    'notif.minAgo': 'min',
    'notif.hourAgo': 'h',
    'notif.dayAgo': 'd',

    // Proposal detail
    'prop.type.general': 'General',
    'prop.type.ask': 'Ask',
    'prop.type.spend': 'Spend',
    'prop.type.prodcast': 'Prodcast',
    'prop.type.general.desc': 'Regular discussion and voting — no funds involved.',
    'prop.type.ask.desc': 'Request funds from the group treasury for your business.',
    'prop.type.spend.desc': 'Shared group expense — for a vendor or service.',
    'prop.type.prodcast.desc': 'Promote a project to investors via the investment portal.',
    'prop.title.ph.general': 'e.g. Raise the monthly contribution',
    'prop.title.ph.ask': 'e.g. Business working-capital loan',
    'prop.title.ph.spend': 'e.g. Training workshop fee',
    'prop.title.ph.prodcast': 'e.g. Irrigation farming project',
    'prop.amount': 'Amount (TSH)',
    'prop.amount.ph': 'e.g. 500000',
    'prop.recipientPhone.ph': 'e.g. 0712345678',
    'prop.vendorName.ph': 'e.g. Supplies shop',
    'prop.expenseCategory': 'Expense Category',
    'prop.expenseCategory.ph': 'e.g. Supplies, Training, Event...',
    'prop.fundingGoal': 'Funding Goal (TSH)',
    'prop.fundingGoal.ph': 'e.g. 5000000',
    'prop.timeline.ph': 'e.g. 6 months',
    'prop.impact': 'Expected Impact',
    'prop.impact.ph': 'e.g. Increase revenue by 30%',
    'prop.desc.label': 'Description',
    'prop.desc.optional': '(optional)',
    'prop.projectDesc.ph': 'Describe your project to investors...',
    'prop.info.general': 'All group members will be able to vote once the proposal is created.',
    'prop.info.ask': 'Funds will be transferred directly to your wallet once the vote passes.',
    'prop.info.spend': 'All group members will be able to vote once the proposal is created.',
    'prop.info.prodcast': 'Once the vote passes, the project appears to investors on the portal.',
    'prop.cancel': 'Cancel',
    'prop.attachment': 'Attachment (photo/file)',
    'prop.attachment.add': 'Upload a photo or PDF',
    'prop.attachment.helper': 'A photo or PDF up to 2MB — e.g. a receipt, price quote, or project photo.',
    'prop.attachment.err': 'Unsupported or too-large file.',
    'prop.attachment.view': 'Open attachment',
    'prop.err.titleRequired': 'A proposal title is required.',
    'prop.err.amountInvalid': 'Enter a valid amount.',
    'prop.err.phoneRequired': "Enter the recipient's phone number.",
    'prop.err.goalInvalid': 'Enter a funding goal.',
    'prop.err.createFailed': 'Failed to create the proposal.',
    'prop.err.genericFailed': 'Something went wrong.',
    'prop.success.created': 'Proposal created!',
    'prop.backToGroup': 'Back to Group',
    'prop.by': 'by',
    'prop.open': 'Open',
    'prop.closed': 'Closed',
    'prop.abstain': 'Abstain',
    'prop.totalVotes': 'Total',
    'prop.votes': 'votes',
    'prop.needed': 'needed',
    'prop.yourVote': 'Your vote',
    'prop.recipient': 'Recipient',
    'prop.recipientPhone': "Recipient's phone",
    'prop.status.paid': 'Paid',
    'prop.status.pending': 'Pending',
    'prop.leaderAction': 'Leadership Action',
    'prop.status': 'Status',
    'prop.amountPh': 'e.g. 5000',
    'prop.chooseMember': 'Choose a member',
    'prop.notEnoughVotes': 'The proposal did not get enough votes',
    'prop.notEnoughVotesTail': 'You can reopen the vote or create a new proposal.',
    'prop.detailsHeading': 'Proposal Details',
    'prop.field.fundingGoal': 'Funding Goal',
    'prop.field.timeline': 'Timeline',
    'prop.field.impact': 'Expected Impact',
    'prop.field.projectDesc': 'Project Description',
    'prop.field.vendor': 'Vendor',
    'prop.field.expenseCategory': 'Expense Category',
    'prop.field.businessPurpose': 'Business Purpose',
    'prop.type.pillGeneral': 'General',
    'prop.type.pillAsk': 'Funding Request',
    'prop.type.pillSpend': 'Expense',
    'prop.type.pillProdcast': 'Prodcast (Investor)',
    'prop.results': 'Voting Results',
    'prop.yes': 'Yes',
    'prop.no': 'No',
    'prop.vote': 'Cast Vote',
    'prop.votingClosed': 'Voting is closed',
    'prop.canChange': 'You can change your vote at any time.',
    'prop.allCanVote': 'All group members can vote.',
    'prop.amountRequested': 'Amount Requested',
    'prop.paymentStatus': 'Payment Status',
    'prop.pending': 'Pending',
    'prop.passed': 'Proposal passed ✓ — you can pay from the group treasury.',
    'prop.amountTzs': 'Amount (TZS)',
    'prop.executing': 'Executing...',
    'prop.disburse': 'Execute Payment (Disburse)',
    'prop.fromTreasury': 'It will be paid from the group treasury balance.',
    'prop.reopenVoting': 'Re-open voting',
    'prop.err.notAllowed': 'You are not allowed to view this proposal.',
    'prop.err.loadFailed': 'Failed to load proposal.',
    'prop.err.voteFailed': 'Failed to cast vote.',
    'prop.err.invalidAmount': 'Enter a valid payment amount.',
    'prop.err.payFailed': 'Failed to execute payment.',
    'prop.err.reopenFailed': 'Failed to re-open voting.',
    'prop.reopenSuccess': 'Voting re-opened. Members can now vote.',
    'prop.chooseRecipient': 'Choose a recipient.',
    'prop.paid': 'Payment complete! (Funds disbursed)',

    // Share group
    'share.button': 'Share',
    'share.title': 'Share Group',
    'share.desc': 'Invite others to join your group',
    'share.copy': 'Copy Link',
    'share.copied': 'Copied!',
    'share.more': 'More',
    'share.msgJoin': 'Join the group',
    'share.msgCode': 'Use group code',
    'share.msgOn': 'on WashikaDAU',

    // Contribution frequency
    'grp.freq.label': 'Contribution Frequency',
    'grp.freq.monthly': 'Monthly',
    'grp.freq.weekly': 'Weekly',
    'grp.freq.contribAmount': 'Contribution',
    'grp.settings.title': 'Group Settings',
    'grp.settings.save': 'Save Changes',
    'grp.settings.saving': 'Saving...',
    'grp.settings.saved': 'Settings saved!',
    'grp.settings.leadershipOnly': 'Only leadership can change settings.',

    // Investor portal
    'inv.nav.overview': 'Overview',
    'inv.nav.projects': 'Projects',
    'inv.nav.groups': 'Groups',
    'inv.nav.wallet': 'Wallet',
    'inv.nav.profile': 'Profile',
    'inv.investorPortal': 'Investor Portal',
    'inv.publicPage': 'Public Page',
    'inv.signOut': 'Sign Out',
    'inv.contact': 'Contact',
    'inv.welcome': 'Welcome',
    'inv.overviewSub': 'Here is an overview of investment opportunities across the WashikaDAU network.',
    'inv.stat.activeProjects': 'Active Projects',
    'inv.stat.approvedProdcasts': 'Approved Prodcasts',
    'inv.stat.fundingSought': 'Funding Sought',
    'inv.stat.totalRequested': 'Total requested',
    'inv.stat.groups': 'Groups',
    'inv.stat.active': 'Active',
    'inv.stat.members': 'Members',
    'inv.stat.regions': 'regions',
    'inv.recentlyVoted': 'Recently Voted Projects',
    'inv.viewAll': 'View all',
    'inv.activeGroups': 'Active Groups',
    'inv.investmentProjects': 'Investment Projects',
    'inv.approvedByVote': 'projects approved by member vote',
    'inv.noProjects': 'No projects yet',
    'inv.noData': 'No data yet',
    'inv.wallet.title': 'nTZS Wallet',
    'inv.wallet.sub': 'Deposit, withdraw, or transfer funds via the Base network.',
    'inv.wallet.balance': 'Wallet Balance',
    'inv.deposit': 'Deposit',
    'inv.withdraw': 'Withdraw',
    'inv.recentTx': 'Recent Transactions',
    'inv.noTx': 'No transactions yet',
    'inv.profile.title': 'Your Profile',
    'inv.profile.sub': 'Your investor information',
    'inv.edit': 'Edit',
    'inv.verified': 'Account Verified',
    'inv.pending': 'Pending Verification',
    'inv.pendingSub': 'Our team will reach out within 2 business days',
    'inv.field.fullName': 'Full Name',
    'inv.field.email': 'Email',
    'inv.field.company': 'Company',
    'inv.field.country': 'Country',
    'inv.field.type': 'Type',
    'inv.field.minInvestment': 'Min Investment',
    'inv.field.maxInvestment': 'Max Investment',
    'inv.fund': 'Fund',
    'inv.seekingVote': 'Seeking Vote',
    'inv.communityApproved': 'Community Approved',
    'inv.awaitingApproval': 'Awaiting community approval',
    'inv.communityVote': 'Community vote',
    'inv.contribution': 'Contribution',
    'inv.about': 'About the project',
    'inv.expectedImpact': 'Expected impact',
    'inv.noDataSub': 'Prodcast projects will appear here once approved by groups',
    'inv.noProjectsSub': 'Groups will submit projects here through the voting process',
    'inv.approvedByVote2': 'approved by member vote',
    'inv.col.group': 'Group',
    'inv.col.members': 'Members',
    'inv.col.contribution': 'Monthly Contribution',
    'inv.col.projects': 'Projects',
    'inv.fundingGoal': 'Funding goal',
    'inv.timeline': 'Timeline',
    'inv.backToProjects': 'Back to projects',
    'inv.members': 'members',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('sw');

  // Restore the saved language on mount
  useEffect(() => {
    const saved = typeof window !== 'undefined' ? window.localStorage.getItem('wd-lang') : null;
    if (saved === 'en' || saved === 'sw') setLanguage(saved);
  }, []);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const next = prev === 'sw' ? 'en' : 'sw';
      if (typeof window !== 'undefined') window.localStorage.setItem('wd-lang', next);
      return next;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['sw']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
