import { NextRequest, NextResponse } from 'next/server';
import pool from '@/lib/db';
import { getAuthTokenPayload } from '@/lib/auth';

export const dynamic = 'force-dynamic';

/**
 * GET /api/member/groups/[id]/wall?period=week|month|year
 *
 * The Ukuta — one brick per member per period, gold when their contribution
 * landed. Built from ntzs_transactions rather than monthly_contributions:
 * that table was never populated, and the ledger is where contributions
 * actually settle, so it is the only source that tells the truth.
 *
 * The period is a zoom level on the same data. A group paying weekly cannot
 * read its own health off monthly rows, and a group two years old cannot see
 * its history six months at a time.
 */
type Period = 'week' | 'month' | 'year';

const PERIODS: Record<Period, { count: number; trunc: string; step: 'day' | 'month' | 'year'; stepBy: number }> = {
  week:  { count: 8, trunc: 'week',  step: 'day',   stepBy: 7 },
  month: { count: 6, trunc: 'month', step: 'month', stepBy: 1 },
  year:  { count: 4, trunc: 'year',  step: 'year',  stepBy: 1 },
};

export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const auth = getAuthTokenPayload(request);
  if (!auth) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await ctx.params;
  const groupId = Number.parseInt(id, 10);
  if (!Number.isFinite(groupId)) {
    return NextResponse.json({ error: 'Invalid group id' }, { status: 400 });
  }

  const client = await pool.connect();
  try {
    const meRes = await client.query(
      `SELECT m.id FROM members m
         JOIN group_members gm ON gm.member_id = m.id
        WHERE m.user_id = $1 AND gm.group_id = $2 AND gm.status = 'active'
        LIMIT 1`,
      [auth.userId, groupId],
    );
    if (meRes.rows.length === 0) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    const myMemberId = (meRes.rows[0] as { id: number }).id;

    // Roster in a stable order so a member keeps the same column between
    // renders — the wall is only legible if bricks do not move around.
    const membersRes = await client.query(
      `SELECT m.id, m.full_name
         FROM group_members gm
         JOIN members m ON m.id = gm.member_id
        WHERE gm.group_id = $1 AND gm.status = 'active'
        ORDER BY gm.joined_date NULLS LAST, m.id`,
      [groupId],
    );

    const raw = request.nextUrl.searchParams.get('period');
    const period: Period = raw === 'week' || raw === 'year' ? raw : 'month';
    const cfg = PERIODS[period];

    // The bucket key is computed in SQL so Postgres owns the calendar maths —
    // week boundaries in particular are not something to reimplement in JS.
    const paidRes = await client.query(
      `SELECT DISTINCT t.from_member_id AS member_id,
              to_char(date_trunc('${cfg.trunc}', t.created_at), 'YYYY-MM-DD') AS bucket
         FROM ntzs_transactions t
        WHERE t.to_group_id = $1
          AND t.purpose = 'contribution'
          AND t.from_member_id IS NOT NULL
          AND t.created_at >= date_trunc('${cfg.trunc}', CURRENT_DATE)
                              - INTERVAL '${cfg.stepBy * (cfg.count - 1)} ${cfg.step}'`,
      [groupId],
    );

    // The same buckets, generated by Postgres, so the row keys line up exactly
    // with the keys above rather than depending on JS and SQL agreeing.
    const bucketRes = await client.query(
      `SELECT to_char(d, 'YYYY-MM-DD') AS bucket
         FROM generate_series(
                date_trunc('${cfg.trunc}', CURRENT_DATE)
                  - INTERVAL '${cfg.stepBy * (cfg.count - 1)} ${cfg.step}',
                date_trunc('${cfg.trunc}', CURRENT_DATE),
                INTERVAL '${cfg.stepBy} ${cfg.step}'
              ) AS d
        ORDER BY d`,
    );

    const members = (membersRes.rows as { id: number; full_name: string }[]).map((m) => ({
      id: m.id,
      name: m.full_name,
      isMe: m.id === myMemberId,
    }));

    const paidSet = new Set(
      (paidRes.rows as { member_id: number; bucket: string }[]).map((r) => `${r.member_id}:${r.bucket}`),
    );

    const label = (iso: string) => {
      const d = new Date(`${iso}T00:00:00Z`);
      if (period === 'year') return String(d.getUTCFullYear());
      if (period === 'week') return `${String(d.getUTCDate()).padStart(2, '0')}/${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
      return d.toLocaleString('en-GB', { month: 'short', timeZone: 'UTC' }).toUpperCase();
    };

    // Oldest first, so the wall reads bottom-up like something built.
    const rows = (bucketRes.rows as { bucket: string }[]).map(({ bucket }) => {
      const bricks = members.map((m) => ({
        memberId: m.id,
        paid: paidSet.has(`${m.id}:${bucket}`),
        isMe: m.isMe,
      }));
      const count = bricks.filter((b) => b.paid).length;
      return {
        month: bucket,
        label: label(bucket),
        bricks,
        count,
        // A period nobody paid into is the one thing a chama needs to spot at a
        // glance, so it is flagged rather than left to be counted.
        empty: count === 0,
      };
    });

    return NextResponse.json({
      members,
      total: members.length,
      rows,
      myMemberId,
      period,
    });
  } catch (error) {
    console.error('[group wall]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  } finally {
    client.release();
  }
}
